### ISSUE TITLE
Update MozFest 2016 website home page

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#1]
Currently the website is still in 2015 mode

To update we need to add
- [x]  2016 dates
- [x] 2015 VIDEO
- [x] Stay in touch information
- [x] Remove 2015 pages such as
  - [ ] Tickets
  - [ ]  schedule
  - [ ] remote
  - [ ] Fringe events

It would be really great to get the home page in 2016 shape asap cc @edrushka

**Comment by edrushka** [comment]
[Ticket filed in Plan](https://github.com/MozillaFoundation/plan/issues/773). Fingers crossed!

**Comment by edrushka** [comment]
I also added "update the team page" since many partners will probably be checking there.

**Comment by edrushka** [comment]
Done!
