### ISSUE TITLE
Scope Tweet #mozfest page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#10]
Link to current page: https://twitter.com/intent/tweet?text=%23mozfest&source=webclient

**What needs updating June:** 
- [ ] add sample text for tweet
- [ ]  

**Other thoughts/ideas**:
- [ ] Add content from our own twitter page- like a scribble page

**Comment by edrushka** [comment]
@KevZawacki any suggestions for a tweet to pre-fill? It should remain relevant until the next major site update before the festival (early October).

**Comment by KevZawacki** [comment]
@edrushka Is there a certain action we want to drive -- ticket sales? Sharing the website? This could be a good opportunity.

**Comment by Saallen** [comment]
Could the narrative but about "join us at the festival" so that it relates to tickets, submission etc....maybe the link is always back to the main page of the website

**Comment by KevZawacki** [comment]
Sounds good. How about:

I'm attending #mozfest, the biggest event for & by the open Internet movement. Join me & @Mozilla in London: mzl.la/mozfest

**Comment by edrushka** [comment]
Nice! Works for me. @Saallen?

**Comment by edrushka** [comment]
@vazquez here's the tweet to auto-populate. Note that I filed a separate ticket #31 to update the shortlink (it currently points to the 2015 site).

I'm attending #mozfest, the biggest event for & by the open Internet movement. Join me & @Mozilla in London: mzl.la/mozfest
