### ISSUE TITLE
Keep current homepage CTA

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/2016.Mozillafestival.org#101]
Don't update homepage CTA to "sign up" yet

<img width="679" alt="screen shot 2016-09-20 at 9 56 31 am" src="https://cloud.githubusercontent.com/assets/2896608/18680464/bbc26e16-7f18-11e6-9e94-1b3c99401317.png">

We'll keep "Buy a Ticket" for a little longer (note that colours should be updated to 2016 colours)

<img width="794" alt="screen shot 2016-09-20 at 9 56 17 am" src="https://cloud.githubusercontent.com/assets/2896608/18680444/a2d9efbe-7f18-11e6-8cda-72d00f925171.png">

**Comment by edrushka** [comment]
@mmmavis The red text and button are fine. Can you please change the grey text to:  MozFest 2016 is a chance to build something, grow your network and get inspired. Sound interesting?

**Comment by mmmavis** [comment]
@edrushka this looks good?

![fireshot capture 66 - mozfest 2016 - http___localhost_9090_](https://cloud.githubusercontent.com/assets/2896608/18686617/613f6d36-7f31-11e6-8852-09756a09d838.png)

**Comment by edrushka** [comment]
ship it! 🚢 

Thanks mavis!
