### ISSUE TITLE
Coordinate D+D timings with Space Wranglers

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/2016.Mozillafestival.org#102]
- Encourage wranglers to promote D+Ds within their space
- Encourage wrangles to program fewer sessions / close spaces during D+Ds

@edrushka @Saallen Let me know how I can help!

**Comment by edrushka** [comment]
Closing this, since you sent the emails to the SW's @KevZawacki. Feel free to re-open if there is more to do here.
