### ISSUE TITLE
Create D+D signage and posters for venue

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/2016.Mozillafestival.org#104]
- Promote D+D on screens throughout venue
- Promote D+D with slick posters (complete with speaker headshots) throughout venue

If design cannot commit resources, @edrushka and @kevzawacki to create.

**Comment by kristinashu** [comment]
Here are tickets for video screens around Ravensbourne https://github.com/MozillaFoundation/Mozfest2016_production/issues/170
and for the posters https://github.com/MozillaFoundation/Mozfest2016_production/issues/167

Does that cover it?

**Comment by edrushka** [comment]
Yes, I think that's it for print/digital.

**Comment by edrushka** [comment]
Closing, as this conversation is happening in https://github.com/MozillaFoundation/Mozfest2016_production/issues/167
