### ISSUE TITLE
Add space icons to Spaces and Sessions page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/2016.Mozillafestival.org#106]
Icons are done so I will prep them for the website, then @mmmavis can add them to https://mozillafestival.org/spaces-and-sessions

**Comment by kristinashu** [comment]
@mmmavis here are the icons (note, they are slightly different than the schedule app ones which are better at small sizes):

[Space icons.zip](https://github.com/MozillaFoundation/2016.Mozillafestival.org/files/499297/Space.icons.zip)

Widths for each icon:
open science: 45px
localisation: 28px
youth zone: 43px
journalism: 43px
open badges: 38px
Digital Arts and Culture: 42px
Fuel The Movement: 47px
Demystify the Web: 31px
Dilemmas in Connected Spaces: 38px
MozEx: 43px

**Comment by mmmavis** [comment]
@kristinashu I believe the width values are supposed to be doubled. I've reflected that changes in the PR.
