### ISSUE TITLE
Design "live festival" landing page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#107]
Based on the discussion in https://github.com/MozillaFoundation/Mozfest2016_production/issues/16, which led to the [decisions documented here](https://docs.google.com/document/d/1HQkzvdWCcTxnFOWlL-6gPrM4xtIivZwo0b7DINnM9ZU/edit#), we'll need a slight redesign of the landing page for when the festival is live to accommodate the following:
- [x] live streaming/archive of videos
  -- 1 Saturday morning keynote 
  -- 11 Dialogue and Debates speakers
- [x] highlight medium blog 
- Note that a few things will change in the nav (e.g. remove ticket sales, add link to schedule) but that shouldn't affect design.

**Comment by edrushka** [comment]
One thought is to highlight the 11 individual speakers [similar to what XOXO does](http://xoxofest.com/).
It could be a static photo with the name and title of speech. Clicking before the festival would link to their entry on the schedule app (?). Clicking after the festival would link to their archived talk.

**Comment by edrushka** [comment]
cc @xmatthewx @hannahkane @kristinashu

**Comment by kristinashu** [comment]
How are we planning to live stream?

cc @mmmavis for technical input

**Comment by edrushka** [comment]
We will be livestreaming on Facebook so the website can either embed that stream (not sure if that's possible) or just link to it. CC-ing @simonwex and @KevZawacki who were at the tech scoping meeting a while back.

**Comment by kristinashu** [comment]
For during the festival, I recommend we have a very simple solution: intro text, image and one link to the live stream on Facebook.

After the festival, we can look at archiving all the talks individually (like https://xoxofest.com/).

**Comment by edrushka** [comment]
I am on board with very simple. Kevin has reached out to the MoCo Facebook streaming peeps and is setting up a meeting for next week, so we'll have some of the technical details soon.

**Comment by kristinashu** [comment]
Linking content: [bios](https://docs.google.com/document/d/14VXDQcdKjOztX62HxYbnHXrPjwD-xR3ATY03KcsPVSo/edit) & [pics](https://drive.google.com/drive/folders/0B-BKZVAww2KHRzlGOWNfc19rZGc)

**Comment by kristinashu** [comment]
@edrushka here is a design for the most straightforward way we could do this https://redpen.io/xv5545c0e96da474b5

**Comment by edrushka** [comment]
Awesome - this is essentially the MVP. Are there any options to jazz this up a bit with a speakers photo, or mainstage photo or a graphic that suggests live content?

Example photos:
- https://www.flickr.com/photos/mozfest/22867318371/in/album-72157660181490099/
- https://www.flickr.com/photos/mozfest/22433077929/in/album-72157658567152683/
- https://www.flickr.com/photos/mozfest/22455735387/in/album-72157658649418943/
- https://www.flickr.com/photos/mozfest/22252930503/in/album-72157658649418943/

**Comment by kristinashu** [comment]
Cool, I'll try those.

Can we get some copy? @KevZawacki would you be the one writing this?

**Comment by edrushka** [comment]
**Blue Banner text:**
MozFest
The world's leading festival for the open internet movement.
Watch MozFest's speaker series live, beginning  Oct. 29 11 a.m. BST

**CTA Banner text** (draft, but this should work for the mockup)
Missed MozFest this year?
Sign up for MozFest updates and be first in line to get your tickets for 2017
[links to ti.to form]

**Comment by kristinashu** [comment]
Based on our chat, I will:
- Updated copy
- Removed blog CTA
- Add speaker photos + names

**Comment by kristinashu** [comment]
@edrushka I've added the speakers and a couple banner image options https://redpen.io/p/nfb876a7968c868f1b

**Comment by edrushka** [comment]
Ohhh very nice! 💃 I like the both options!
@KevZawacki @HPaulJohnson @Saallen If you have comments can you please leave them in the redpen by EOD Monday? Thank you. (Reminder - this is for what the website will look like during and for a few weeks after MozFest.)

**Comment by Saallen** [comment]
Done!

**Comment by KevZawacki** [comment]
Done! This design is beautiful -- can/will it be live in the weeks before, too?

**Comment by kristinashu** [comment]
Thanks everyone! I've updated redpen with the few bits of feedback https://redpen.io/p/nfb876a7968c868f1b and will prep the file for @mmmavis to start implementing.

**Comment by edrushka** [comment]
This looks beautiful. Thanks @kristinashu 🌷

**Comment by kristinashu** [comment]
Here's the implementation ticket https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/110
