### ISSUE TITLE
Update and add partner logos

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#108]
1. Replace EPIK logo with Youth Led EU (Just text, there is no official logo. Same font as EPIK logo is fine)
   Links to: https://www.facebook.com/YouthLedEU/
2. Add new logo: Open Technology Institute https://na-production.s3.amazonaws.com/images/oti-web-5.min-200x100.png
   Link to: http://www.newamerica.org/oti/

**Comment by mmmavis** [comment]
@kristinashu can you help process these images? 😉

**Comment by kristinashu** [comment]
Here you go:
![opentechnology](https://cloud.githubusercontent.com/assets/1068783/19201288/e53562b4-8c81-11e6-8855-52c2c8de17b1.jpg)
![youthledeu](https://cloud.githubusercontent.com/assets/1068783/19201287/e5253cc2-8c81-11e6-9a55-91e9c939eba8.jpg)
