### ISSUE TITLE
Scope Volunteer page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#11]
Link to current page: https://2015.mozillafestival.org/volunteer

**What needs updating June:** 
- [ ] Update content
- [ ] Add link to 2016 sign up page
- [ ] Freshen page

**Other thoughts/ideas**:
- [ ]

**Comment by edrushka** [comment]
@SpikeUK we're refreshing the MozFest website with updated info for June 1 when the Call for Proposals opens. Can you take a look at https://2015.mozillafestival.org/volunteer and let me know if you need any changes to that copy. The last paragraph about the MozPubs will definitely need to be edited -  we can remove it altogether for now, if you like.

Also, do you or @Saallen  have a link to the volunteer signup ti.to page?

Thanks!

**Comment by edrushka** [comment]
Here's the updated text from Spike (via email).

Volunteers are integral to what we do at Mozilla, and MozFest is no different. The annual festival could not take place without the time, dedication and love of our local volunteers.

Drawn from the local community, volunteers at MozFest do so much, from running the welcome desk and arranging swag bags to assisting press and helping with programming. We try to place people in roles they’re most interested in, and rotation of roles is encouraged. We provide training before the event, and we host several volunteer socials.

Volunteers are asked to share four hours of their time. As a thank you, we’ll cover the festival’s ticket cost. Volunteers also receive meals and a MozFest t-shirt. Unfortunately, we cannot cover travel to and from the event or provide accommodation.

The MozFest team meets bi-monthly in Mozilla’s London office, so come say hi and learn more.

Sign up here to be a MozFest volunteer.

**Comment by edrushka** [comment]
@vazquez ^ that text is ready for implementation. We'll have the ti.to link (for the last sentence) by May 30.

**Comment by vazquez** [comment]
Text has been changed!

**Comment by vazquez** [comment]
The only thing we are missing here is the ti.to link. Otherwise it's good to go.

**Comment by SpikeUK** [comment]
Volunteer sign-up page has been created and is now live at https://ti.to/Mozilla/mozfest2016-volunteers
Spike

**Comment by edrushka** [comment]
^ @ScottDowne - just need you to add that link to the last line of text 'Sign up here to be a MozFest volunteer.' and this page is done. Thanks.

**Comment by ScottDowne** [comment]
Proposed changed here: https://github.com/mozilla/mozillafestival.org/pull/382

Needs a reviewer.

**Comment by ScottDowne** [comment]
I landed the patch, it's on the develop branch.

Not sure currently where that builds, but closing this as I'm confident the code landed.
