### ISSUE TITLE
(by Oct 24) Implement "live festival" landing page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/2016.Mozillafestival.org#110]
Based on design in #107 and seen here https://redpen.io/qa0ea25b456b54b2ed

All the speaker images and the new banner image are here: https://drive.google.com/open?id=0B2irLVDJivhLM0dnVWdTbkpINzQ

We might need to do some QA and adjust the home banner to make it crop properly (so the face isn't hidden behind the text or cut off).

.ai file is here: https://drive.google.com/open?id=0B2irLVDJivhLZTE2aEFEOGpVSVU

Assuming @mmmavis would be working on this? cc @edrushka

**Comment by edrushka** [comment]
@hannahkane can you please confirm who the dev will be who will implement these changes to the MozFest website?

**Comment by hannahkane** [comment]
The Connecting Leaders team is tasked with MozFest work, so I would think @mmmavis. @mmmavis - does that work for you?

cc @simonwex

**Comment by edrushka** [comment]
@mmmavis This could be done after the schedule work has been handed off to Dan. Ideally this would go live sometime during the week of Oct 24. Drop dead deadline would be Oct 28.

**Comment by mmmavis** [comment]
@edrushka this shouldn't take me too long to build since it's mainly just adding people's name, pic, and Twitter to the page. I should be able to get it live on Oct 24 (Monday) unless a later date is preferred.

Note that I won't be managing spreadsheet much but I still need to work on 
- adding GA to schedule app
- set up Mozbot so that schedule app can be easily updated when needed

**Comment by edrushka** [comment]
Thanks for clarifying!

And let's aim for the 24th and we'll have a few days of wiggle room if other dev stuff comes up.

Thanks @mmmavis 🌷

**Comment by kristinashu** [comment]
Few notes about links:
- "Watch live" links to https://www.facebook.com/mozilla
- Bio pics and names aren't links, only the twitter handles link
- @edrushka do you know what "Sign up" should do?

**Comment by edrushka** [comment]
It should like to a ti.to form - the question is which one. I've opened #111 as I expect there will be a bit of discussion around this.

**Comment by edrushka** [comment]
Link to ti.to sign up form is here: https://ti.to/Mozilla/mozfest-2017

**Comment by edrushka** [comment]
ti.to sign up form has been beautified - it's ready to go! https://ti.to/Mozilla/mozfest-2017
