### ISSUE TITLE
Confirm CTA for 'live' version of site

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#111]
For the 'live' version of the site (Oct 24 until whenever we change it - probably Nov or Dec), the CTA I've drafted is:

Missed MozFest This Year?
Sign up for MozFest updates and be first in line to get your tickets for 2017.

You can see it on t[his redpen](https://redpen.io/qa0ea25b456b54b2ed)

@Saallen @KevZawacki @HPaulJohnson @steviebenton does this work for you?

If so, Sarah, what ti.to form do we send them to? Do we need to make a new one?

**Comment by KevZawacki** [comment]
@edrushka Works for me!

**Comment by StevieBenton** [comment]
Looks good to me, too. If there is space, can we have something asking them for content?

**Comment by marcwalsh-zz** [comment]
@edrushka The easiest thing to do would be to create the MozFest 2017 event on ti.to and send them to the register interest form on there. It'll mean that all the signups can be emailed through ti.to and it can be tracked on next year's events stats.

**Comment by edrushka** [comment]
@StevieBenton no space on the landing page as we can only have 1 CTA per banner

@marcwalsh Great! Are you able to set up the form and paste the link here?

**Comment by Saallen** [comment]
I set up the 2017 to.ti page. Whomever set the 2016 updates page, would
they like to add the design treatments again?

**Comment by edrushka** [comment]
Ti.ti link is here: https://ti.to/Mozilla/mozfest-2017
needs some sprucing up before we start linking to it.

**Comment by edrushka** [comment]
Filed a sprucing up ticket here https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/114 Need Hannah or Matthew to assign.

Closing this, as I don't think there's anything else for discussion.
