### ISSUE TITLE
Spruce up 2017 ti.to form

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#114]
Need to add an image and icon to the 2017 Sign up for more information form.

https://ti.to/Mozilla/mozfest-2017 should look nice, like: https://ti.to/Mozilla/mozfest-2016/

@hannahkane @xmatthewx I think Ricardo did this last year so I'll leave you to assign. We can duplicate look of 2016 exactly or update slightly with the style guide. Not a design priority IMO.

I think this is principally a dev task, though not positive since Ricardo could do both.

**Comment by xmatthewx** [comment]
I'd hope we would just need to add a new banner image. Let's discuss on our stand. Maybe best to have Mavis take a peek under the hood to gather requirements?

**Comment by edrushka** [comment]
+1 @hannahkane can I assign to Mavis to check out the requirements?

**Comment by hannahkane** [comment]
WFM, if Mavis has the bandwidth.

**Comment by edrushka** [comment]
@mmmavis can you let us know the requirements to make https://ti.to/Mozilla/mozfest-2017 look nice, like: https://ti.to/Mozilla/mozfest-2016/
- MVP: add a banner image
- Nice to haves: add icon and styled text

Note that the 2017 page won't sell tickets - it just needs to collect email addresses.

**Comment by mmmavis** [comment]
### 2016 tito page: ( https://ti.to/Mozilla/mozfest-2016/ )
- banner, background color, and some text are set in https://ti.to/Mozilla/mozfest-2016/admin/settings/homepage
- icon and text are set in https://ti.to/Mozilla/mozfest-2016/admin/settings/basics
- banner: https://d2z6c3c3r6k4bx.cloudfront.net/uploads/event/banner/1010238/86c31ff0a9230c89f1306b41616c3850.jpg

### 2017 tito page: ( https://ti.to/Mozilla/mozfest-2017/ )
- banner, background color, and some text are set in https://ti.to/Mozilla/mozfest-2017/admin/settings/homepage
- icon and text are set in https://ti.to/Mozilla/mozfest-2017/admin/settings/basics

I can help upload images (banner and icon) if needed but for text I think it'll be easier for the program staff to enter it directly on tito.

/cc @kristinashu for image files

**Comment by edrushka** [comment]
ty Mavis! 🐻 

@kristinashu  I'm fine with using the main banner image from https://mozillafestival.org/

**Comment by kristinashu** [comment]
Ok, I'll resize the home page image (no text overtop) and the logo in 2016 pink.

**Comment by kristinashu** [comment]
Here's a crop banner image and a pink gear logo:
![titobg](https://cloud.githubusercontent.com/assets/1068783/19496822/223dddca-953e-11e6-8b43-023e96f6f4e7.jpg)
![76x76 2x](https://cloud.githubusercontent.com/assets/1068783/19496811/18bfb0ca-953e-11e6-93bc-087b6b4cec1b.png)

**Comment by mmmavis** [comment]
@edrushka I've uploaded the 2 images onto https://ti.to/Mozilla/mozfest-2017/

**Comment by edrushka** [comment]
Sorry @kristinashu - I meant the blue/pink glitch image. Not the photo of Raegan. The Raegan photo seems a bit weird on ti.to.

**Comment by edrushka** [comment]
The two women looking awestruck from https://mozillafestival.org/spaces-and-sessions works as well. Perhaps you could prep both in case the blue/pink doesn't work without a text overlay.

**Comment by kristinashu** [comment]
Lets go with the photo:
![titobg](https://cloud.githubusercontent.com/assets/1068783/19526163/64d9e058-95d8-11e6-994e-adb4c5068adc.jpg)

**Comment by mmmavis** [comment]
https://ti.to/Mozilla/mozfest-2017/ updated. @erikad I'll leave this to you to add copy directly via Tito's dashboard. 👍

**Comment by edrushka** [comment]
Done! https://ti.to/Mozilla/mozfest-2017
