### ISSUE TITLE
Add Internews to the partners tab of team page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#116]
Please add this logo to https://mozillafestival.org/team/partners
![a_color_horizontal_tag](https://cloud.githubusercontent.com/assets/4515662/19477972/95812b4e-9538-11e6-84ee-da8ca03c57c6.jpg)
cc @kristinashu for making grey scale

Link to http://internews.org/

**Comment by kristinashu** [comment]
@mmmavis here's the logo 
![internews](https://cloud.githubusercontent.com/assets/1068783/19496660/4f42dfe2-953d-11e6-875a-69258f97985c.jpg)
