### ISSUE TITLE
Update Space & Sessions page with Schedule

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#118]
#### 1) Update Spaces and Sessions paragraph

Change to:

Spaces are physical and thematic learning hubs based around a broad topic, like science, art, or journalism. A Space is made up of sessions, which are hands-on, educational gatherings based around a specific topic, like “Using Crafts to Teach Localization Processes.” Sessions generally run 30-90 minutes. 

[View the MozFest 2016 schedule](https://app.mozillafestival.org/)
#### 2) Update links for individual spaces

Each space currently has linked text that reads "See the sessions in this space." Those links go to Github. 

Replace links so they go to the individual space in the schedule app. For example, in Digital Arts and Culture, the linked line "See the sessions in this space" should point to https://app.mozillafestival.org/#_space-digital-arts-and-culture

**Comment by mmmavis** [comment]
@edrushka should link for MozEx stays as https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BExperience%5D+Moz+Ex%22 ?

**Comment by edrushka** [comment]
Ohh good catch. Let's make the link for MozEx point to their Issuu page: https://issuu.com/mozfest/docs/mozex For this one can you change the linked text to read
**See the artwork in this space.**

**Comment by edrushka** [comment]
cc @Saallen ^ On the Spaces page on the website, every other space goes to Schedule, but since MozEx isn't really doing sessions, I suggest we point to the Issuu page. Cool?

**Comment by edrushka** [comment]
Luca said yes. Let's do this.
