### ISSUE TITLE
Scope Fringe Events page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#12]
Link to current page: https://2015.mozillafestival.org/fringe

**What needs updating June:** 
- [ ] Create new google form for submissions
- [ ] Update the content to 2016
- [ ]  Refresh page

**Other thoughts/ideas**:
- [ ] Remix the google form to allow for logos?-
- [ ]

**Comment by edrushka** [comment]
@Saallen do we still want to start accepting Fringe events in June? If so, can you link me last year's submission form?

**Comment by Saallen** [comment]
hI
@mmmavis made this form https://docs.google.com/a/mozillafoundation.org/forms/d/1XCjIF3ptc4XAl7ql-pkhhIDc7dERYshrLHOFZgjdIUY/viewform
I can update it quickly if needed

**Comment by edrushka** [comment]
Simple form, but the actual Fringe Page looks quite good: https://2015.mozillafestival.org/fringe

@vazquez as someone who actually submitted a Fringe event, do you have any suggestions? I'm fine to simply update this for 2016 if it works as-is.

**Comment by vazquez** [comment]
I agree with you @edrushka. I don't think there is anything needed to change. The process was super simple to add a fringe event!

**Comment by edrushka** [comment]
Cool - let's leave it as-is. @Saallen can you please update the form so it says 2016?

**Comment by edrushka** [comment]
@Saallen ETA on this?

**Comment by Saallen** [comment]
Here is the 2016 form- a carbon copy from last year
https://docs.google.com/a/mozillafoundation.org/forms/d/10l8_PtMgHvhxh4qZcGqTzWm3a0QhuTQOIVnn4Bx8qKc/edit#

**Comment by Saallen** [comment]
@edrushka Looking at last years form- would it be possible to have some titles beside the information to help clarify the info such as
When:
Where:
Sign up:

**Comment by edrushka** [comment]
@vazquez here is the updated form: https://docs.google.com/a/mozillafoundation.org/forms/d/10l8_PtMgHvhxh4qZcGqTzWm3a0QhuTQOIVnn4Bx8qKc/edit# It's exactly the same as last year's, but with updated dates.

Not sure if you'll have time for this, but is it possible to make it so when the events get displayed on the actual page, can the When, Where and Sign Up fields be indicated as Sarah requested in the comment above?

**Comment by vazquez** [comment]
The form now shows the sample dates with 2016 as the year. I didn't get a chance to do this though:

> Not sure if you'll have time for this, but is it possible to make it so when the events get displayed on the actual page, can the When, Where and Sign Up fields be indicated as Sarah requested in the comment above?

**Comment by mmmavis** [comment]
Do we wanna add a link to the fringe page somewhere on the site? 😉

**Comment by edrushka** [comment]
Yes! Last year it had its own icon on the bottom of the page under the CTA. I think Ricardo just hid it.

See it here: https://2015.mozillafestival.org/

**Comment by mmmavis** [comment]
fringe page is upppppp https://mozillafestival.org/fringe 🆙

**Comment by mmmavis** [comment]
Let me know if there's any tweak you want me to add. Otherwise feel free to close this tickettt YAY
