### ISSUE TITLE
Post-festival changes to site

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#120]
Site updates to go live _immediately_ after the festival (Sunday night or Monday morning) based on what's on staging: http://mozillafestival-org-staging.herokuapp.com/
#### Top Nav
- [x] Replace TICKETS with PULSE. Links to:  https://mzl.la/mozfest-pulse?keyword=mozfest (confirm in https://github.com/MozillaFoundation/Mozfest2016_production/issues/200)
- [x] Replace LOCATION with BLOG. Links to: https://medium.com/mozilla-festival/tagged/mozfest2016
#### Main (purple) banner text
- [x] change 'Welcome to MozFest' to 'MozFest'
- [x] change 'Watch MozFest's speaker series live, beginning Oct 29, 11am BST' to 'Watch videos from MozFest 2016'
- [x] change button text from 'Watch Live' to 'Opening Keynote'. Button links to: AirMo video of Mark & Gunner - link to come
- [x] Add a second button that reads "Speakers Series' and links to: TBD (cc @KevZawacki will there be a tag for all vids in FB so we can link to them all in one place? If not, AirMo will probably have a tag and we can point there)
#### Speaker Series section
- [x] Link each speaker's picture to their individual talk. Collected in #121

**Comment by edrushka** [comment]
I'm aware we link to blog twice. Once in top nav. Once in bottom icon. That's fine.

**Comment by alanmoo** [comment]
I've started these changes in https://github.com/mozilla/mozillafestival.org/tree/post-festival-updates, will update that as I get more links.

**Comment by alanmoo** [comment]
These are all done, with some polish thrown in once https://github.com/mozilla/mozillafestival.org/pull/485 closes
