### ISSUE TITLE
Links to archived Speaker Series talks

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#121]
This is a collection of the archived talks. Note these are _not_ the edited, polished versions Dosed is preparing. This is the interim solution until Dosed's videos are ready in Nov/Dec.

Zeynep Tufekci
Brian Behlendor
Maggie Vail
Mark Surman
Sahar Aziz
Katherine Maher
Chris Soghoian
Ashe Dryden
Volker Birk
Katharina Borchert
Simone Browne
Eliot Higgins

**Comment by edrushka** [comment]
cc @KevZawacki for filling in links as soon as we have them

**Comment by KevZawacki** [comment]
Hi, all.

All links:

[Zeynep Tufekci, Brian Behlendorf, and Maggie Vail](https://air.mozilla.org/mozfest-speaker-series-our-digital-lives/) (Block titled "Our Digital Lives")
- Brian starts at 28:33
- Maggie starts at 50:45

[Mark Surman, Mitchell Baker, and Sahar Aziz](https://air.mozilla.org/mozfest-speaker-series-surveillance-and-privacy-online/) (Block titled "Surveillance and Privacy Online.")
- Sahar Aziz starts at 24:55

[Katherine Maher, Chris Soghoian, and Ashe Dryden](https://air.mozilla.org/mozfest-speaker-series-privacy-and-harassment-on-the-internet/) (Block titled "Privacy and Harassment on the Internet.")
- Chris Soghoian starts at 19:15
- Ashe Dryden starts at 41:27

[Volker Birk and Katharina Borchert](https://air.mozilla.org/mozfest-speaker-series-building-a-secure-and-equal-web/) (Block titled "Building a Secure and Equal Web.")
- Katharina Borchert starts at 15:15

[Simone Browne and Eliot Higgins](https://air.mozilla.org/mozfest-speaker-series-inclusion-and-secrets-online/) (Block titled "Inclusion and Secrets Online.")
- Eliot Higgins starts at 17:29

@edrushka and I are working on creating a specialized link that directs to all D+D talks.

**Comment by alanmoo** [comment]
Is there a plan to add chapter markers to the videos? Trying to figure out if I should link to the start of the hour video for each person in the block, or if there's a timecode that would be best.

**Comment by alanmoo** [comment]
Also, Mitchell isn't on the homepage. Should I add her?

**Comment by edrushka** [comment]
No need to add Mitchell.

**Comment by KevZawacki** [comment]
@alanmoo I don't think there's a plan to add chapter markers, since we'll have separate, more polished versions of each talk ready in ~two weeks.

In the meantime: Are timecodes doable/easy? If so, I can share the precise time each new speaker starts.

**Comment by alanmoo** [comment]
@KevZawacki I think the only way to link to a timecode is by creating chapter markers in AirMo (which doesn't seem that difficult, FWIW, but I'm also fine just linking to the talk block.)

**Comment by alanmoo** [comment]
I've created a saved search that seems to work- https://air.mozilla.org/search/?ss=20

**Comment by KevZawacki** [comment]
If it helps, I've added speaker start times to the comment above

**Comment by alanmoo** [comment]
I've opened a PR to add timestamps to the links.
