### ISSUE TITLE
Scope About page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#13]
Link to current page: https://2015.mozillafestival.org/about

**What needs updating by June**
- [ ] Add 2015 to the timelines
- [ ] Update numbers
- [ ] Freshen page

**Other thoughts/ideas**:
- [ ]

**Comment by edrushka** [comment]
see @ScottDowne's comments in #20

**Comment by Saallen** [comment]
Ala Freshing up the page @edrushka 💣

**Comment by edrushka** [comment]
@vazquez we'll need a graphic or image for 2015 (I'll update the copy).

**Comment by edrushka** [comment]
@Saallen please review proposed text 

**Paragraph at top of page:**
The seventh-annual MozFest will be held in London, from Friday, Oct. 28 - Sunday, Oct. 29. MozFest is an annual celebration of the open Internet movement. It's where passionate technologists, educators, and makers come together to explore the future of the open Web.

**2015 and 2016 entries on the timeline:**

2015
In 2015, we focused on leadership, advocacy and impact. We placed a particular emphasis on training tomorrow's leaders, empowering participants to make a positive difference on the Web, and working toward universal web literacy.

2016
This year, we'll highlight how the Internet movement’s boldest, most game-changing ideas can come from anyone, anywhere. We'll examine how issues like Web literacy, online privacy and encryption are relevant across the globe, and address challenges faced by people who don't yet feel they are welcome on the Web.

**Comment by edrushka** [comment]
@Saallen also, do you have updated numbers for the little circles? Need:
- number of attendees
- number of countries participants came from
- number of sessions

**Comment by Saallen** [comment]
👍 on update copy
I dont have reliable numbers for 2015 as we had issues with rego- but  I **think** we had 1600 in the building
- 325 sessions
- I dont have the full number of countries 
- is there other data I could provide here to freshen up the page?

**Comment by edrushka** [comment]
I'll leave countries as 50+. I think this is the most relevant data to communicate. In 2017 we'll be able to add in a number for salons/talks.

This page will look "freshened" (teehee) because we're adding Mark's speech bubble at the top, as decided in #7

**Comment by edrushka** [comment]
@vazquez this page isn't 100% ready because we're still waiting for Mark's speech bubble but the other sections are set if you want to get started on them.

**Mark's Speech Bubble**
_still to come_

**Updated  number bubbles:**
1600+ 
Over 1.6K attendees

50+
Participants from more than 50 countries

325
Workshops & sessions

**Paragraph under number bubbles:**
The seventh-annual MozFest will be held in London, from Friday, Oct. 28 - Sunday, Oct. 29. MozFest is an annual celebration of the open Internet movement. It's where passionate technologists, educators, and makers come together to explore the future of the open Web.

**2015 and 2016 entries on the timeline:**

2016
This year, we'll highlight how the Internet movement’s boldest, most game-changing ideas can come from anyone, anywhere. We'll examine how issues like Web literacy, online privacy and encryption are relevant across the globe, and address challenges faced by people who don't yet feel they are welcome on the Web.

2015
In 2015, we focused on leadership, advocacy and impact. We placed a particular emphasis on training tomorrow's leaders, empowering participants to make a positive difference on the Web, and working toward universal web literacy.

**Comment by vazquez** [comment]
@edrushka Changes made! Is there anything else for this page? We could close this issue and open another one just for mark's speech bubble if it's a blocker.

**Comment by edrushka** [comment]
Sounds good. I made a new ticket for the speech bubble #34. Can I see the new 2016 icon/image before we close this?

**Comment by vazquez** [comment]
@edrushka 

Oh sure! I'm using this:

![screen shot 2016-05-24 at 2 55 41 pm](https://cloud.githubusercontent.com/assets/1119821/15516173/a02bda22-21bf-11e6-9dcb-ca62c62c02b1.png)

**Comment by edrushka** [comment]
Cute!

**Comment by Saallen** [comment]
Hi @edrushka @vazquez  just adding a little note that the logo you used is on the flag is the logo for "Open Web of things" from 2013 and 2014 http://2014.mozillafestival.org/tracks/index.html
which doesnt match the content of the paragraph

**Comment by vazquez** [comment]
Okay, I have changed it to a globe

![screen shot 2016-05-25 at 9 53 23 am](https://cloud.githubusercontent.com/assets/1119821/15542389/8eb7f704-225e-11e6-8a43-135868b857fa.png)

**Comment by Saallen** [comment]
Thanks @vazquez 🌎

**Comment by edrushka** [comment]
@vazquez Mark has signed off on the speech bubble. Here it is:

Dear Friends,

I like to think of the Mozilla community as a reflection of the Internet: Creative. Eclectic. Speaking many languages, spanning many disciplines, always open to new ideas.   

This is most apparent at MozFest, the annual celebration of our community and the greater open Internet movement. Three days each year, we gather together and discuss, debate, create and hack to build a better Internet. We’re a diverse crew: Scientists from the UK. Educators from Kenya. Technologists from Shenzhen. 

When we come together this year, we want to celebrate our diversity. We want to show that the open Internet movement’s boldest, most game-changing ideas can come from anyone, anywhere. We have the proof: Over the past year, the next generation of open Internet leaders have campaigned for net neutrality in India; taught digital skills in Nairobi and Cape Town; and explored the future of the Internet of Things in Berlin.

This year at MozFest, we also want to do our duty as outlined in the Mozilla Manifesto: Ensure the Internet is a global public resource, open and accessible to all. That means teaching web literacy to more people in more places. It also means asking hard questions about what an ‘inclusive Internet’ really means. We need to actively address the challenges faced by people who don't yet feel they are welcome on the Web.

We have our work cut out for us -- there’s no shortage of threats to the open Internet. Online privacy and important safeguards like encryption are in jeopardy. And walled gardens are making the Web more closed and less hackable. 

At MozFest this year, we’ll work on solutions to these issues and so many others. Our MozFest brainstorms, sessions and creativity always inspire me, and I can’t wait to see what we build together this year.

See you in London,
—Mark Surman
