### ISSUE TITLE
Scope Festival Team page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#14]
Link to current page: https://2015.mozillafestival.org/team

**What needs updating (by when):** **October**
- [ ] put Sarah's bio at top (and update role to Director?)
- [ ] add Erika's bio
- [ ] edit Michelle's role
- [ ] Update all bios
- [ ] Freshen page

**Other thoughts/ideas**:
- [ ]

**Comment by edrushka** [comment]
@Saallen for the current round of updates, I propose we:
- update your role to director (or whatever title you want) and move you to the top. 
- next is gunner
- next is misty
- next is Spike
- next can be me. I'll write a bio.
- next is Mark W.

Let me know how you'd like to feature Michelle. We can remove her altogether for now, or add her as a 'special advisor'.

I'll update everyone's text to reference MozFest 2016 instead of 2015.

We can do full bio re-writes closer to the festival.

Does that work for you?

**Comment by edrushka** [comment]
My suggested bio:

Erika Drushka is the Production Manager for MozFest 2016. With a background in documentary film making, advocacy and fundraising, Erika has spent the last three years on the MozFest communications team. This year, Erika has shifted her focus at Mozilla to building network strength in the open internet movement through convenings.

Maybe this picture? https://www.flickr.com/photos/mozillaeu/15629697531/in/album-72157648568431188/

**Comment by edrushka** [comment]
### April update:
- [ ] make a row with 4 columns instead of a vertical list
- [ ] order of row: Sarah, Erika, Spike, Gunner

#### Sarah text:

Sarah Allen
Festival Producer
Sarah Allen is this year’s festival producer. When she is not focused on MozFest, she helps with other Mozilla convenings in London and beyond. Sarah draws her experience from a diverse events background having worked with creative and inspiring companies, such as Movember Europe, Secret Cinema and CSM iLUKA. MozFest 2016 will be Sarah’s fourth festival.

#### Erika text:

Erika Drushka
Program Designer
Erika Drushka is the Program Designer for MozFest 2016. With a background in documentary film making, advocacy and fundraising, Erika has spent the last three years on the MozFest communications team. This year, Erika has shifted her focus at Mozilla to building network strength in the open internet movement through convenings.
-Erika photo: https://www.dropbox.com/s/q0g8j2c0h55h9ow/MozFest.jpg?dl=0

#### Spike text:

Spike
Volunteer Coordinator
Chris Foote (known as “Spike”) is the Volunteer Coordinator for MozFest 2016. A life-long professional Electronic Engineer with a passion for science and technology, he is a volunteer with global organisations such as CrisisCommons, CrisisMappers, OpenStreetMap (OSM), Humanitarian OSM Team (HOT), StandbyTaskForce (SBTF). He has co-organised a very successful London-based monthly Meetup group for people involved in or interested in ICT4D (Information and Communication Technologies for Development) as well as organising countless BarCamps and Hackathons. This is Spike's sixth MozFest, and his fourth as Volunteer Coordinator.

#### Gunner text

 exactly the same - no changes

**Comment by Saallen** [comment]
Confirming Spike is happy with his bio.
I might ask that my bios first line is changed...."this years festival producer" reads now to me this is my first year as the producer....can we remove it?

**Comment by edrushka** [comment]
Revised copy for Sarah:

Sarah Allen
Festival Producer
Sarah Allen is MozFest's producer. When she is not focused on MozFest, she helps with other Mozilla convenings in London and beyond. Sarah draws her experience from a diverse events background having worked with creative and inspiring companies, such as Movember Europe, Secret Cinema and CSM iLUKA. MozFest 2016 will be Sarah’s fourth festival.

**Comment by edrushka** [comment]
@Saallen do we want to add more bios for June 1, or update this in Aug when the call for proposals closes?

**Comment by Saallen** [comment]
We can update in August 👍

**Comment by edrushka** [comment]
WFM. Closing this for now.
