### ISSUE TITLE
Scope Participation Guidelines page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#15]
Link to current page: https://2015.mozillafestival.org/guidelines

**What needs updating by October:** 
- [ ] Link to the full Mozilla guidelines
- [ ] Add consequences for not respecting guidelines
- [ ] Freshen page

**Other thoughts/ideas**:
- [ ] Link to the broader mozilla guidelines

**Comment by Saallen** [comment]
@edrushka I think we should say that there will be consequences but I am hestitant to call them out on the page as every incident is different.Closer to the time we will add a number for ppl to call, other ways to highlight and incident and yes- say that consquences will be actioned for those not respecting the guidelines.

**Comment by edrushka** [comment]
Here are the best practices for a _complete_ Code of Conduct/Participation Guidelines ([source](http://www.ashedryden.com/blog/codes-of-conduct-101-faq#coc101examples)):
- statement of unacceptable behavior 
- how the policy will be enforced
- how and whom to make an incident report to
- training and reference materials for organizers, staff, and volunteers on how to respond to incident reports
  MoCo modified its official policy in late March: https://www.mozilla.org/en-US/about/governance/policies/participation/

I feel that the current page is good, if we:

1) link to the official policy in the first paragraph e.g.

R-E-S-P-E-C-T
The Mozilla Festival respects Mozilla's [community participation policy](https://www.mozilla.org/en-US/about/governance/policies/participation/). These guidelines cover our behaviour as participants, facilitators, space wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

2) Update the Raising Issues at MozFest section by including some copy about consequences e.g.
MozFest participants violating these participation guidelines may be sanctioned or expelled from the conference at the discretion of the conference organisers.

Thoughts @Saallen ?

**Comment by Saallen** [comment]
I agree with all but would like to chat more about the 2nd point 
pre festival weekend we will have a variety ways of contacting me including a phone number that have two default connections if I am unconntactable so that will be updated closer to the event.
I dont agree with the use of the word santioned here but do think you are right we should have something here.
I might advice we state something like " MozFest organised reserve the right to refuse admission to anyone violating these guidelines and/or to take further action.

**Comment by edrushka** [comment]
I like your edit but want to make sure it covers people that are behaving poorly at the actual event (i.e. once they've already been admitted).

How about:
MozFest organisers reserve the right to refuse admission to anyone violating these guidelines, and/or take further action including expulsion from the event.

**Comment by Saallen** [comment]
🆒

**Comment by edrushka** [comment]
@vazquez here are the copy changes.

**1)  link to the official policy, so the first paragraph reads:**

R-E-S-P-E-C-T
The Mozilla Festival respects Mozilla's [community participation policy](https://www.mozilla.org/en-US/about/governance/policies/participation/). These guidelines cover our behaviour as participants, facilitators, space wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

**2) New text for "raising issues at MozFest" section**

If you believe you‘re experiencing practices at MozFest which don‘t meet the above policies, or if you feel you are being harrassed in any way, please immediately contact the Festival Producer, Sarah Allen.

Email: festival@mozilla.org

At the festival venue, contact the info desk and they will immediately find the Festival Director for you.

MozFest organisers reserve the right to refuse admission to anyone violating these policies, and/or take further action including expulsion from the event.

**3) Change the first sentence of the 'working in the open' section to read:**
Because working open is one of our core values, MozFest program planning is done in the open on Github (check out our repo [here](https://github.com/MozillaFoundation/mozfest-program-2016)).
