### ISSUE TITLE
Scope Submission Process page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#16]
Link to current page: https://2015.mozillafestival.org/submission-process

**What needs updating by May:** 
- [ ] Update link to 2016 repo 
- [ ] LInk to submission form 
- [ ] Update text slightly
- [ ] Freshen page

**Other thoughts/ideas**:
- [ ]

**Comment by ScottDowne** [comment]
Some more info is in here: https://github.com/MozillaFoundation/plan/issues/805

It's a lot of info though.

Some things we have talked about including in this work:
- [ ] transactional email for submissions with info on how to engage further. @edrushka who would be the one to create this email copy?
- [ ] l10n for the submission form as an option. It would still default everyone to en-US even if they have an updated language, as this language change changes the meta about their submission and not _just_ the language they want to use to submit.
- [ ] github integration
- [ ] google form integration
- [ ] front end changes, including a 2-step form that handles some logic.

**Comment by edrushka** [comment]
@ScottDowne I can write, or at least wrangle, the copy for the confirmation email. Made a ticket here #28

**Comment by ScottDowne** [comment]
@Saallen or @edrushka I know we talked about the form fields and what we'll need for this year, with the multiple sections/logic.

However, is that written somewhere? Is this essentially what we have so far? https://public.etherpad-mozilla.org/p/festival-sessioncuration

**Comment by ScottDowne** [comment]
Ah, I remember! it's here: https://docs.google.com/a/mozillafoundation.org/forms/d/19eD51TFUfklPS57XccwP_YPkDZ4DVl_aB4olaJmvgNU/edit

**Comment by Saallen** [comment]
Hey @ScottDowne I started to map out the steps here
#29

**Comment by edrushka** [comment]
@Saallen Proposed copy refresh for the Submission page:

We use GitHub to manage, review and curate sessions for MozFest. GitHub allows us to openly collaborate, and it provides a record for how the festival program came together. 

When the Call for Proposals closes on August 1, Space Wranglers will review all proposals and choosing sessions that best align with their Space objectives. You can follow this process on our [GitHub repo](https://github.com/MozillaFoundation/mozfest-program-2016).

Unfortunately, not all proposals will be accepted; the weekend simply is not long enough. But there's good news: everyone who proposed a session will be gifted a free ticket to the festival. 

Click here to submit a proposal for MozFest 2016 [link to form].

**Comment by Saallen** [comment]
@edrushka this is great new copy but we might leave the info about a free ticket off to assist with ticket sales and in case anything changes.

**Comment by edrushka** [comment]
@vazquez here's the copy for this page

We use GitHub to manage, review and curate sessions for MozFest. GitHub allows us to openly collaborate, and it provides a record for how the festival program came together.

When the Call for Proposals closes on August 1, Space Wranglers will review all proposals and choosing sessions that best align with their Space objectives. You can follow this process on our [GitHub repo](https://github.com/MozillaFoundation/mozfest-program-2016).

[Submit a proposal for MozFest 2016](links to form).

**Comment by edrushka** [comment]
The only thing we're waiting on here is the link to the call for proposals.

**Comment by Saallen** [comment]
Not sure if you are looking for this version but here is the final edit for the Google form I have been working on
https://docs.google.com/a/mozillafoundation.org/forms/d/19eD51TFUfklPS57XccwP_YPkDZ4DVl_aB4olaJmvgNU/edit

**Comment by edrushka** [comment]
@Saallen 

The terms for the exhibit should be a single checkbox, not yes/no radio buttons.

The terms should be the last question in that section.

Also, in that section, why aren't all the spaces listed under the question 'Is there another space you believe this exhibit could be shown within'?

**Comment by Saallen** [comment]
@edrushka all Spaces listed now and terms moved down

**Comment by edrushka** [comment]
Thanks Sarah 🐝 🌻 
The translated forms don't contain all the spaces. Can we ping Heather for that?

**Comment by edrushka** [comment]
Oh wait, I think it's just that one Moz Ex question that's not listing them all. I think we can copy and paste from the other sections.

**Comment by Saallen** [comment]
Good catch- no Space names should be translated as they are titles and names- I will make direct edits now to each form  @edrushka I am going to go through all forms now to ensure all are listed exactly the same 👓
