### ISSUE TITLE
Scope Session page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#17]
Link to current page: https://2015.mozillafestival.org/sessions

**What needs updating (by when):** 
- [ ]  Space narrative - **May**
- [ ]  Pathway narrative- **October**

**Other thoughts/ideas**:
- [ ] Maybe we should label the link from the landing page Spaces & Sessions 
- [ ] Add glossary to this page
  - [ ] How to navigate the scedule/festival- with link to orientation sessions

**Comment by Saallen** [comment]
@edrushka agreed - title of page doesn't match the content fully

**Comment by edrushka** [comment]
@vazquez would it be bad UX to change the name of Sessions to 'Spaces & Sessions' in the footer? You can see it here in the footer of the 2015 page: http://2015.mozillafestival.org/

**Comment by edrushka** [comment]
@Saallen for the June 1 update I propose we delete the entire Spaces and Pathways paragraph (we can add it back in Sept.) and change the heading across the photo to 'Spaces' (right now it reads Sessions).

**Comment by edrushka** [comment]
Also, do we intend to include icons? New spaces will need icons, which I don't know if we can swing by June 1. I suggest we remove them for now and add them later in the fall, which will give the design team a chance to rethink them in general.

**Comment by Saallen** [comment]
@edrushka in agreement with the name change.
All spaces will need icons but with this small timeline before the opening of the call we can remove icons until September . The icons are good wayfinding tools so we should have the back up on the website in order to assist that.

**Comment by edrushka** [comment]
WOOO! It's finally ready!

@mmmavis here is the content for this page: https://docs.google.com/document/d/1TyncLzVRiMt-bwAa9aX99oIdG6G6WiDzYupsvYjnIE8/edit#  A few notes:
- This page is now called Spaces and Sessions. Please update the banner text if Ricardo didn't do that already
- You can delete all the space icons for now. We'll add them back in in the fall
- Wranglers are names only (no handles) for now
- Localisation is spelled with an S, not a Z this year (British spelling)

**Comment by mmmavis** [comment]
@edrushka cool, I'll have a PR up for this today. 👍
