### ISSUE TITLE
New page proposal: Blog

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#18]
Last year we asked all the wranglers to blog about MozFest- and put them on Webmaker site-
It was not the best looking site and the layout meant that old posts were lost.

Is there a way to link this blog into the mozfest site as a page but allowing for a tagging system (such as space names) to allow people to sort through them?

**Comment by edrushka** [comment]
whoa! I didn't see this until now. Great idea! I'm working on scoping the June 1 site updates so I'll add this in.

**Comment by vazquez** [comment]
As discussed, I'm flagging this task as requiring a moderate amount of time to complete. This seems to be the only large task in the website scoping. All other tasks are small-scope and doable 👍

**Comment by edrushka** [comment]
And as we agreed in https://github.com/MozillaFoundation/plan/issues/805 - we will implement this page when the CMS is ready (not for the June 1st website update).

**Comment by edrushka** [comment]
@vazquez For June 1 Update, we'll add a Blog link to the bottom nav. It should point to medium.com/mozfest-2016 as discussed in #26. 

Can it open in a new tab so we don't take people 100% away from the site, or is that bad practice?

**Comment by vazquez** [comment]
Totally.
