### ISSUE TITLE
Update MozFest site with 2016 info

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#19]
- [x] **Add 2016 dates on landing page**
  October 28-30, 2016
  Ravensbourne, London
- [x] **Update video on landing page with new vid**
  New vid is here: https://vimeo.com/154774646
  If we're embedding directly from their Vimeo, Dosed can change the title/description/tags etc. They can also customize the way it looks when it’s embedded (hide/show different parts of the player and change the colours).
- [x] **Replace 'Buy a Ticket' CTA with 'Sign up for more information'**
  The white banner text under the image can read:
  H1: Help Make the Web a Better Place
  H2: Receive festival news and updates by email
  Button text: Sign up 
- [x] **Update Team page**
  We're working on this in https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/14 I'll update this ticket when the text and images are finalized (will aim for EOD Wednesday). 
- [x] **Hide pages that aren't currently relevant:** (these will return in June and September)
      Tickets
      Schedule
      Remote
      Fringe events
      Submission process
      Sessions
      Pathways

**Comment by mmmavis** [comment]
@edrushka do you know if we plan to archive the 2015 site? Right now https://mozillafestival.org/ goes to https://2015.mozillafestival.org/ . Should we change it so that it will go to https://2016.mozillafestival.org/ instead?

**Comment by edrushka** [comment]
I believe that's what we've done for the last few years. Is there a reason _not_ to do this?

**Comment by mmmavis** [comment]
Nope, wanted to double check before I file a DevOps ticket. :+1:

**Comment by edrushka** [comment]
@mmmavis the Festival Team page updates are ready in #14

**Comment by mmmavis** [comment]
DevOps ticket created: https://github.com/MozillaFoundation/mofo-devops/issues/309

**Comment by edrushka** [comment]
@Saallen can you please provide the link where we're sending people who want to sign up for more info?

**Comment by mmmavis** [comment]
(@alicoding correct me if I'm wrong )

i dont think Basket has signup pages available for us to link to. It's more of the API that we post our data to. This means we probably need to create a form on the MozFest site to take user data.

**Comment by alicoding** [comment]
You are correct (based on my knowledge)

**Comment by Saallen** [comment]
Hey @mmmavis @alicoding and @edrushka I have added you all as admin for the ti.to platform for mozfest 2016- you can have a look around and see the [sign up page](https://ti.to/Mozilla/mozfest-2016) and other intergration info

**Comment by mmmavis** [comment]
Thanks @Saallen . I didn't know ti.to has this! :grin:

**Comment by Saallen** [comment]
No worries @mmmavis have a play around the admin site

**Comment by mmmavis** [comment]
@edrushka the "done in the open" link on https://2015.mozillafestival.org/guidelines links to the to-be-removed "Submission Process" page. What should we do with it? Just make it not hyperlinked?

**Comment by Saallen** [comment]
@mmmavis @edrushka  what do you think  if we update the line here to link to last years [Github repo](https://github.com/mozilla/mozfest-program), we can just need to change the text slightly.
Then in June hopefully we will be able to link to  2016 repo :question:

**Comment by edrushka** [comment]
That works for me. So we will:
- remove/hide "Submission Process" page as planned
- alter text on "Guidelines" page to read 

Because working open is one of our core values, MozFest program planning is done in the open on Github (check out our 2015 repo [here](https://github.com/mozilla/mozfest-program)). We hope participants will benefit from this culture of transparency and collaboration during the Festival, and will continue to work with an open ethos in their projects after Mozfest. We recommend bookmarking WorkOpen.org and reading through the interviews with passionate advocates for open practices.

**Comment by mmmavis** [comment]
most of the changes are up on https://mozillafestival-org-staging.herokuapp.com/ for review! I'm working on things @edrushka mentioned in her last comment - but they should appear on that Heroku app soon.

**Comment by mmmavis** [comment]
https://mozillafestival-org-staging.herokuapp.com/guidelines updated!

**Comment by edrushka** [comment]
wooo! 

@Saallen if you're able to take a look at this before you head out, let us know if you see anything amiss.

**Comment by Saallen** [comment]
Nice-  :tulip: 

Should the workopen.org be a link too on the final paragraph??

**Comment by mmmavis** [comment]
both https://mozillafestival-org-staging.herokuapp.com/team and https://mozillafestival-org-staging.herokuapp.com/guidelines are updated now (with Sarah's revised bio and hyperlink workopen.org) :smile: 

Can I get a r+ on the staging site? :wink:

**Comment by edrushka** [comment]
For https://mozillafestival-org-staging.herokuapp.com/team:
- capitalize the 'Internet' in last line of my bio (sorry! that's my bad copy editing :P )

For https://mozillafestival-org-staging.herokuapp.com/guidelines
- In the 'Raising Issues' section, change the first line to: 

If you believe you‘re experiencing practices at MozFest which don‘t meet the above policies, or if you feel you are being harrassed in any way, please immediately contact the Festival Producer, Sarah Allen.
- In the 'Working in the Open' section, remove the last sentence and replace it with:

Learn more about [how we work open at Mozilla](https://wiki.mozilla.org/Working_open).

^ just a note that that change is because workopen.org now links to some etherpad instance.

**Comment by mmmavis** [comment]
staging site updated! :dancers:

**Comment by edrushka** [comment]
R+ on both /guidelines and /team! :star2:

**Comment by Saallen** [comment]
Hey @edrushka  and @mmmavis When do we go live with this swanky new website?

**Comment by edrushka** [comment]
We're currently blocked on https://github.com/MozillaFoundation/mofo-devops/issues/316

**Comment by Saallen** [comment]
Danke!

**Comment by edrushka** [comment]
Done! Thanks @mmmavis :tulip: :rose: :sunflower:
