### ISSUE TITLE
Kick off work for 2016 website

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#2]
Key website release moments

*\* Early April*\* - Release 1- Save the date- vidyo 
**May** - Release 2- Call for Proposals + 2016 narrative 
**Sept** Update 3 Accepted proposals on the site
**Oct**  Update 5- festival site 
**Nov** Update 6- post festival

CC @edrushka

**Comment by edrushka** [comment]
Is there any way we can combine 1 and 2 into one update?

**Comment by Saallen** [comment]
We need to update the home page asap as it currently looks like this
https://2015.mozillafestival.org/ 

We cannot wait until May for this to be completed as Space Wrangler and partners need to be able to point towards something as a form of reference. I am already getting emails about where ppl can find more information. 
I dont think leaving the website in its current states does the festival any justice

**Comment by edrushka** [comment]
Agree, we need to update asap.

If we merged updates 1 and 2, we wouldn't necessarily have to wait until May to ship it. I just worry it'll be difficult to get the resources from TPS for 2 separate updates. I can try, but I can't guarantee we'll get it.

**Comment by Saallen** [comment]
Hmm, May update is the space narrative, Marks speech bubble, ticket page and CfP.
Most of this content will be built at the MozRetreat.... :pray:

**Comment by edrushka** [comment]
**Release 1 - Save the Date**
- [Ticket filed.](https://github.com/MozillaFoundation/plan/issues/773)
- Requested deadline of April 8. _Firm_ deadline of April 29.

**Release 2 - Open call for Proposals & 2016 narrative** 
- _Absolutely firm_ deadline of June 1
- we'll add our notes in a ticket for each page
- we'll meet with MW and Jordan to talk about when to integrate the refreshed design 
- I will send Wex and David A an email warning them we need this release shipped by June 1. Firm.
- copy for narrative and space descriptions will come from MozRetreat
- we'll need to dedicate significant effort directly following the retreat to make sure this ships on time. This update (and the Call for Proposal form) will be our main work in the 2nd half of May.

**Comment by edrushka** [comment]
Update: 
- Release 1 is done
- Planning for Release 2 is underway
