### ISSUE TITLE
about page is still talking about things like it's 2015

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/2016.Mozillafestival.org#20]
See here: https://mozillafestival.org/about

You can get here from a link on https://mozillafestival.org/ by going to about.

At a glance, it mentions two out of date things.
1. It references 2015 as the present, and talks about 2015 mezfest in the future tense.
2. The circle matrics under the hero unit are probably out of date.

@edrushka Who else should I ping on this?

**Comment by ScottDowne** [comment]
One more small out of date thing, the https://mozillafestival.org/guidelines link mentions the current repo as the 2015 repo.

**Comment by ScottDowne** [comment]
It's possible things are still being updated, and these issues are known.

**Comment by edrushka** [comment]
Thanks @ScottDowne - this is the best-named ticket I've seen in a while!
I've noted this is the specific ticket for the about page #13
