### ISSUE TITLE
Space narrative- Moz Ex

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#24]
Here is the Narrative for Moz Ex experience

Moz Ex aims to bring together digital artworks that reflect a varied and exciting cross-disciplinary practice around the web. At Mozfest 2016 we will be looking at Web-Literacy, Digital Inclusion and Accessibility, Privacy, Policy and Hacking. For this call, we are particularly focussing on the value of art to society and what role the digital plays in this. We are also very keen to see submissions not only from individual practitioners but cross-disciplinary collaborations that explore the notion of exchange of knowledge and practice with audiences.

**Comment by Saallen** [comment]
The full brief including the actually Call itself is 
Moz Ex
Arts, Culture & Technology

Call for Artists, Designers, Creative Technologists, Makers, Coders, Scientists, Visual Journalists… from techies to newbies! We are inviting submissions of original artwork that relates to the theme of MozFest 2016.
Your submission could be mix-media, photography, video, game, animation or moving image to visual art, graphic design, sculpture. Although the work may be performative or 3D in origin, please consider that it will be exhibited on screens and must be submitted digitally. 
A curated selection of submissions will be shown at MozFest 2016. 
The Brief
Moz Ex aims to bring together digital artworks that reflect a varied and exciting cross-disciplinary practice around the web. At Mozfest 2016 we will be looking at Web-Literacy, Digital Inclusion and Accessibility, Privacy, Policy and Hacking. For this call, we are particularly focussing on the value of art to society and what role the digital plays in this. We are also very keen to see submissions not only from individual practitioners but cross-disciplinary collaborations that explore the notion of exchange of knowledge and practice with audiences.

Submission
On this call we are only accepting digital work. The set-up and curation of the exhibit will be done exploring some DIY solutions, mainly working with a variety of screens, open-source technology and experimenting with layouts.

**Comment by KevZawacki** [comment]
@Saallen Thanks! I'll just be editing the Space narrative aka brief, correct?

**Comment by Saallen** [comment]
@KevZawacki yes, just the brief but I wanted to give you more context around the brief so I added more text from Luca. Can you hold editting as Luca has someone else he wants to show this brief too

**Comment by KevZawacki** [comment]
@Saallen Will do!

**Comment by Saallen** [comment]
Updated copy
Moz Ex aims to bring together digital artworks that reflect a varied and exciting cross-disciplinary practice around the web. At Mozfest 2016 we will be looking at Web-Literacy, Digital Inclusion and Accessibility, Privacy, Policy and Hacking. For this call, we are particularly focussing on the value of art to society and what role the digital plays in this. We are also very keen to see submissions not only from individual practitioners but cross-disciplinary collaborations that explore the notion of exchange of knowledge and practice with audiences.

Terms and conditions
Anything you submit must be your own original work. If your content contains other’s material (e.g. images, video, music, etc) you must have obtained the necessary permissions to use the material.

"As Mozilla is an advocate for working in the open, we recommend you licence your work under a Creative Commons Attribution-ShareAlike 3.0 Unported license, thus increasing the use and reuse of your work while preserving attribution and contributing to the commons.

Alongside the use of your work at MozFest 2016, the Digital Learning team at Tate and the V&A will select artworks to feature in a pop-up show-case as part of the Tate Exchange programme.
Your content will not be used for commercial purposes but we may use your content to promote our platform or project using social media, websites, and other web-platforms."

**Comment by Saallen** [comment]
Looping in @xmatthewx @lovegushwa as per Lucas request
Above is the brief for MozEx and the t&cs for submitting art work under the call

**Comment by lovegushwa** [comment]
@Saallen Sorry to follow up so late on this, noticed I was flagged. 

I haven't seen this in a call for proposals before: 

" Anything you submit must be your own original work. If your content contains other’s material (e.g. images, video, music, etc) you must have obtained the necessary permissions to use the material."

Are we asking for this? or the Tate? Seems like were really limiting parody and remix which conflicts a bit with the remix focus of the advocacy space. 

I don't think apple would have signed off on this:
https://www.youtube.com/watch?v=zsjZ2r9Ygzw

And Campbell soup did not sign off on this: 
https://www.moma.org/learn/moma_learning/andy-warhol-campbells-soup-cans-1962

**Comment by Saallen** [comment]
@lovegushwa HI
This was a tate request- we can chat to luca next week
