### ISSUE TITLE
Set up a Medium publication for 2016

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#26]
Hey @KevZawacki and @Saallen -  in yesterday's stand, the website team felt it makes more sense to go with Medium instead of Wordpress for our blogging platform while we wait for Calypso to be finished. 

Do we need to set up a new publication for 2016 or does it make more sense to continue with the one we started last year?

We'll link to this from the website (I know, not ideal to link viewers away but getting an integrated blog on the site is not in scope for June 1)

**Comment by KevZawacki** [comment]
To get us going, some suggestions for the MozFest 2016 Medium publication:

URL: medium.com/mozfest-2016

Logo: same as last year (see below)

![1-gwjsm0m8cj8yklunvwxbrw](https://cloud.githubusercontent.com/assets/11045250/15370070/417ab234-1d03-11e6-9fc1-f71203e28997.jpg)

Publication title: MozFest 2016 

Publication tagline:  The world’s leading event for and by the open Internet movement

About copy: MozFest isn't just about Mozilla — it's the world’s leading event for and by the open Internet movement. At the Mozilla Festival, bright minds build, debate, and explore the future of our lives online. We tinker with open software, hardware, and practices in the realms of art, journalism, science, technology, and other fields. In 2016, we'll be tackling issues like online privacy, web literacy, digital inclusion, and more.  

@edrushka Thoughts?

([And here's last year's publication for reference](https://medium.com/mozilla-festival).)

**Comment by edrushka** [comment]
Looks good Kevin. I tweaked it slightly to cram in a couple more details. 

MozFest is an annual, hands-on festival for and by the open Internet movement. Every year, bright minds from around the world build, debate, and explore the future of our lives online. We tinker with open software, hardware, and practices in the realms of art, journalism, science, technology, and education. In 2016, we'll celebrate the festival's seventh birthday by tackling issues like online privacy, web literacy, digital inclusion, and more. 

@vazquez any way you could tweak that logo to reflect the purple-pink on this year's landing page?

**Comment by vazquez** [comment]
MozFest 2016 logo available here: 

[https://drive.google.com/open?id=0ByIoeeW0a3R_VlY2MEpOWThWS1k](https://drive.google.com/open?id=0ByIoeeW0a3R_VlY2MEpOWThWS1k)

<img width="188" alt="screen shot 2016-05-18 at 3 46 48 pm" src="https://cloud.githubusercontent.com/assets/1119821/15372711/c35f8df4-1d0f-11e6-9124-f4bc01958ca8.png">

**Comment by Saallen** [comment]
@KevZawacki @edrushka 
I am really liking this paragraphy but what are your thoughts on adding an extra line on the blogs on thei page.
Would it be worth providng clarity that these blogs are written about and for the program at this years festival?

**Comment by KevZawacki** [comment]
@Saallen Good call. We can add this sentence to the end of @edrushka's updated copy:

"In this publication, we invite everyone -- from event facilitators and attendees to remote participants -- to share their thoughts and start conversations."

**Comment by edrushka** [comment]
👍 Do we have anything to pre-populate the publication with, so it's not just blank?

**Comment by KevZawacki** [comment]
@edrushka Not that I can think of, yet. Maybe Mark publishes his speech bubble in blog form?

In any case, as long as we don't promote the blank publication, it's unlikely anyone will stumble across it.

**Comment by KevZawacki** [comment]
Ta-da: [Our Medium publication](https://medium.com/mozfest-2016).

**Comment by edrushka** [comment]
Wooo! Thanks Kevin 💃 

We'll be linking to the blog from the footer of the MozFest site when the Call for Proposals opens on June 1, so it'd be good to get at least 1 thing up there. @omnignorant do you have an ETA for the blog you were planning on writing?

**Comment by Saallen** [comment]
Puurty.

**Comment by KevZawacki** [comment]
We're all set here -- we can open more tickets down the line when we're sourcing individual blogs.
