### ISSUE TITLE
Write confirmation email for session proposal

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#28]
Need a brief email that
- confirms the session has been submitted
- provides info on what happens next
- provides github ticket # 

cc
@ScottDowne @Saallen

**Comment by edrushka** [comment]
DRAFT VERSION 1

Hi <first name>,

Thank you for submitting a session proposal to MozFest!

Our session curation process takes place on Github in the [MozFest 2016 Program repo](https://github.com/MozillaFoundation/mozfest-program-2016). Curation will begin in August when the Call for Proposals closes.

Your session is documented in this issue: <Github ticket # and title>

If you're new to Github, don't be afraid! Sign yourself up for a free account and check out [this tutorial](https://www.pluralsight.com/blog/software-development/github-tutorial) to learn how to view and comment on issues.

If you have questions, please reach out to festival@mozilla.org

Best,
The MozFest Team

**Comment by Saallen** [comment]
This draft email looks great @edrushka 
Other info we could add knowing what answers people look for
-[ ]  Early Sept we will let people know whether their session has been accepted or not
-[ ] let your friends know that you submitted a session for this years mozfest [insert twitter link to  " I just submitted a session to #MozFest, the world’s leading event for and by the open Internet movement. Join me at https://www.mozillafestival.org/]

**Comment by edrushka** [comment]
I'll add in the September info  but a Twitter link makes 3 separate links, which is excessive for a short email. Let's add that to the confirmation screen you get after you press Submit on the form.

**Comment by edrushka** [comment]
VERSION 2

Hi < first name >,

Thank you for submitting a session proposal to MozFest!

Our session curation process takes place on Github in the [MozFest 2016 Program repo](https://github.com/MozillaFoundation/mozfest-program-2016). Curation will begin in August when the Call for Proposals closes. In September, you'll be notified whether your session has been accepted or not.

Your session is documented in this issue: < Github ticket # and title >

If you're new to Github, don't be afraid! Sign yourself up for a free account and check out [this tutorial](https://www.pluralsight.com/blog/software-development/github-tutorial) to learn how to view and comment on issues.

If you have questions, please reach out to festival@mozilla.org

Best,
The MozFest Team

**Comment by edrushka** [comment]
cc @ScottDowne and @cadecairos ^ ready for you to test this text

**Comment by edrushka** [comment]
@cadecairos
