### ISSUE TITLE
Call for Proposals  2016- google form actions within

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#29]
The call for Proposals form for 2016
https://docs.google.com/a/mozillafoundation.org/forms/d/19eD51TFUfklPS57XccwP_YPkDZ4DVl_aB4olaJmvgNU/edit
This form has an introduction and three sections but submitters are only required to fill out 2 sections. 
There are three links to be added

**Particulars**
*Introduction section
Some links required are required for this section which will link to an entire new form
- [ ] Translated form into Spanish
- [ ] Translated form into French
- [ ] Translate form into Arabic

*Section one
In the first section the submissions are asked to add personal information and to choose from a multiply choice list of Spaces. All Mulitply choice answers apart from one, lead to section 3
There is one multiply choice which leads section two - Moz Ex (arts exhibit)

*Section two
As part of this new section specifically for submissions under MozEx - we need a place for the completed digital art works to be uploaded to-
@xmatthewx has been speaking to luca the wrangler for this space and I think they have decided upon a URL. @xmatthewx can you confirm this please?
Once the facilitator has completed this section the form will be completed

*Section 3
All other Multiply choice Space responses lead to this section
Once the facilitator has filled out this section the form will be completed

**Comment by xmatthewx** [comment]
@Saallen – I haven't discussed the form with Luca. We are meeting this week with Jordan to talk about festival design and our time in London. If you have specific questions, I can try to include those.
