### ISSUE TITLE
Decide on Call for Proposal submission location

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#3]
In 2015 we submitted all session to this [repo ](https://github.com/mozilla/mozfest-program) as a curation tool

Can we use Github again this year but have a stream lined process of submission to repo?
Or is there another tool we can use

CC @edrushka

**Comment by edrushka** [comment]
Decision: we'll use this repo, https://github.com/MozillaFoundation/2016.Mozillafestival.org, to curate sessions.

**Comment by edrushka** [comment]
Correction!!  We'll use this repo:  https://github.com/MozillaFoundation/mozfest-program-2016
