### ISSUE TITLE
Moz Ex copyright section needs more thought

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#32]
Hey @Saallen. We looked that the MozEx copyright question on the form during our stand today and noticed a few issues: 
1) Can the response be a single 'I agree' checkbox instead of Yes/No buttons?
2) If people don't agree, what happens? Can they still submit, or should they get an error message saying you must agree to these terms?
3) Can we move this to the last question on that part of the form? As you can see in the attached screenshot, it doesn't look good as-is. We also discussed creating a specific step for it in the form (i.e. you'd answer all the other questions, then press next and it would appear on its own page, and you'd press submit. This would allow us to style it a little better so it's not just an ugly block of bold text).
4) Can we cut down the text any further?

Your thoughts? 
cc @ScottDowne 
![proposal](https://cloud.githubusercontent.com/assets/4515662/15442465/41d6bdc4-1e96-11e6-9b67-9fd352b64803.png)

**Comment by Saallen** [comment]
@edrushka  The T&Cs are very important as we are dealing with artists completed pieces of work so the info outlined is all important. I spoke with Luca and we abrivated some of the text but luca is not comfortable with making more edits. 
Maybe to help break the text as you suggested we can make them a pop up window and ppl then click that yes- they agree.
If ppl dont agree to them we cannot show their work at the festival or with our partners, the Tate and the VnA. 
I have spoke with luca and we adbridged them slightly- I am waiting on the VnA to make final confirmations on this piece below

Anything you submit must be your own original work. If your content contains other’s material (e.g. images, video, music, etc) you must have obtained the necessary permissions to use the material.

"As Mozilla is an advocate for working in the open, we recommend you licence your work under a [Creative Commons Attribution-ShareAlike 3.0 Unported license](https://creativecommons.org/licenses/by-sa/3.0/), thus increasing the use and reuse of your work while preserving attribution and contributing to the commons.

Alongside the use of your work at MozFest 2016, the Digital Learning team at Tate and the V&A will select artworks to feature in a pop-up show-case as part of the Tate Exchange programme.
Your content will not be used for commercial purposes but we may use your content to promote our platform or project using social media, websites, and other web-platforms."

**Comment by edrushka** [comment]
Great! The modified, shorter text in your comment is better. I'm not 100% sure we can hyperlink text in the Google form, though.

What do you think about questions 1-3 in my first comment?

**Comment by Saallen** [comment]
Sorry, thought I answered them
1- Yes I agree :)
2- if ppl don't agree we cannot show their work unfortunately as the Tate will hold a pre festival event, VnA  Museum will promote the art works, and we will have a photographer on site. We want to use their art work as an educational tool too so will reference all the work at the event.

**Comment by Saallen** [comment]
3- I think I asked the question if this could be a pop up window but if not happy for it to be the last question in this section

**Comment by edrushka** [comment]
@ScottDowne 
- we can have a single checkbox instead of a yes/no option
- Sarah has shortened the text (but now it has a hyperlink). 

What do you recommend? Pop-up? Additional step in the form?

**Comment by ScottDowne** [comment]
@edrushka No to popup.

I think we put it near the end, above privacy checkbox, and style it a bit differently to break up the page a bit.

@vazquez thoughts?

**Comment by vazquez** [comment]
Yes, I think the simper approach will be for it to appear last.

**Comment by ScottDowne** [comment]
@vazquez last after privacy checkbox?

**Comment by vazquez** [comment]
Sorry. Second-last.

**Comment by ScottDowne** [comment]
@vazquez so weird idea, what if we gave it a different colour background, white, or something, so it breaks the flow and looks less muddled in with the rest of the content.

**Comment by vazquez** [comment]
We can try that approach, yes. Though as of right now I don't see that as totally necessary. It's not a big change however. We can make that change at any point :)
