### ISSUE TITLE
Mark's speech bubble

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#34]
Opening a separate ticket as this is the last thing needed to finish the About page #13 

cc @KevZawacki @vazquez

**Comment by KevZawacki** [comment]
Mark emailed today about the speech bubble, and noted he'll aim to have feedback our way sometime tomorrow.

**Comment by edrushka** [comment]
Mark signed off on the speech bubble 🌠
