### ISSUE TITLE
Friends and Allies page 

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#35]
We will need later in the year to have a page on the website where we can celebrate our Space Wranglers. 
Last year on the Space page there was hyperlinks and twitter handles added to the space narratives so ppl could learn who our wranglers are for. It would be good to show photos if the team were agreeable- with links to their home companies as a promotional as well as celebratory piece

@edrushka do you think this is more of a schedule piece or could this be integrated onto the website  too?

**Comment by edrushka** [comment]
@Saallen  Do you mean have a friends and allies and _in addition_ to the wranglers page? Or combine them?

**Comment by Saallen** [comment]
@edrushka I think that it would be the same page- we want to thank luca and the companies who he fors for. We want to thank Eva but also internews for allowing her the time to work on the festival.

**Comment by edrushka** [comment]
Sorry, I didn't word that question well. Can we thank both friends/allies and wranglers on the Spaces/Sessions page https://2015.mozillafestival.org/sessions (which is being scoped in #17) or do you want an additional page?

**Comment by Saallen** [comment]
@edrushka Yes, I suppose we could add a piece along the bottom here to say this work would not be possibile without the advice, cooperations and .... of xxxxx

**Comment by edrushka** [comment]
+1 I'd prefer to add this to the bottom of the existing page rather than create a new page.

Confirming that this is for the fall site update, and not June 1.

**Comment by Saallen** [comment]
Yes, this is a fall update :)
However we need to add names to the Space narratives for this release

**Comment by edrushka** [comment]
No problem. I'll be sure to add the names to #17.

**Comment by edrushka** [comment]
Wranglers each have: 
- photo
- bio
- twitter handle

(Possible) additional Friends & Allies page:
- space wranglers (link back to Spaces & Sessions page)
- companies e.g. EPIK, Tate, Arts Award (who give their employees time/permission to participate)
- sponsors
- Participation contributors
- MozFest volunteers
- list of facilitator names with locations - can we do this on a map? there will be around 400
- D&D speakers
- Mozilla staff?? (thank you email to all@ might be more appropriate)
- Vendors??

**Comment by edrushka** [comment]
@Saallen We need to scale back the scope of Friends and Allies acknowledgements based on design constraints and other priorities for the website. A standalone page won't meet the revised goals for the website that emerged after our meeting with Mark.

I propose we find a way to incorporate sponsor/partner logos elsewhere on the site.

**Comment by edrushka** [comment]
Additional ideas for acknowledging people beyond the site, via Claw:
- schedule a series of thank you tweets
- dedicated Medium post listing our Friends and Allies
- Live LED display at the festival
- Printed material at the festival

**Comment by edrushka** [comment]
Closing, as this will not be a separate page.
