### ISSUE TITLE
Space narrative: The “Artistry” in learning: youthZone’s Sandbox

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#36]
In today’s civic society we finds ourselves at the heart of a prescriptive learning system, there to achieve specific objectives, from adverts that follow us telling us what to buy to exams where “Independent thinking” within the system has become a distraction ...

In the #youthZone this year we are working with lots of Teens, Librarians and adults too, to create a space as your independent thinking “Sandbox” for us all to play together and as a tool to challenge our perception as to what a 21st century library is to you. Many of the sessions will be lead by our Raspberry Pi teens with a space dedicated to the “Artistry” of Pi and Virtual reality, this in addition to over 20 extra sessions imagined with you in mind and by you that you could experience in your local library tomorrow.

To do this we are choosing to mash together 2 domains: “Open Source” and “Libraries” to create “Open source library days” where technology is your tool that facilitate “Community play” based on your passions and interest.

We invite you to come and explore with us that “Play” in that sense is truly ageless as a mindset and ask you to help us share with the community through your passions and projects, how we could create your re imagined 21st century library, in one of the last public space where we are all still citizens.

What do you think, come share with us?

---

@edrushka would love you to look over this as I think it needs a small bit of wordsmithing around the  context that this is a space that is open to all ages, offers play to all ages but a large part of the focus is reimagining what community learning looks like through libraries.

**Comment by edrushka** [comment]
cc @KevZawacki

**Comment by Saallen** [comment]
Space Wranglers here are Dorine Flies and Andrew Mulholland
