### ISSUE TITLE
Space Narrative Open Badges 

### ISSUE THREAD

**Issue by mattdigitalme** [MozillaFoundation/2016.Mozillafestival.org#37]
Over the past four years, Digitalme has worked closely with Mozilla to advocate for the Open Badge standard, to implement badge projects in the UK and Europe, and, more recently, take on direct leadership of Open Badges, on behalf of Mozilla. 

Since Mozfest 2014, Over 250 amazing badge projects have been shared via the [Badge the World map](http://www.badgetheworld.org/). As part of this next phase, would like to support the community at Mozfest 2016 to showcase how they have been using badges, to make practical contributions to the Open Badges infrastructure and work together to develop a vision for the future via the Open Badges floor.
- Showcase: Share innovative examples of badge projects happening around the world
- Infrastructure: Contribute to the next version of the open badges technical infrastructure, through Hack the BackPack sessions and discussion around the standard/extensions
- Advocacy: Connect with partners and build networks to further support the expansion of the badge ecosystem worldwide

To ensure all Mozfest revellers get recognition for their efforts during the festival, we are calling on all Space Wranglers and session leaders to consider the opportunity to plug badges into your spaces and sessions, and where appropriate link sessions to run in the Open Badges space. With the plan to recognise and ‘credentialise’ all of the amazing things that happen at MozFest, it really feels like we can help to ramp up the experience throughout the festival and beyond!

**Comment by Saallen** [comment]
<3 you are hacking straight to github @mattdigitalme 
@KevZawacki & @edrushka this is the badges space narrative

**Comment by mattdigitalme** [comment]
@Saallen ;) Does all this sound ok? When the call for proposals goes live we'll get on to getting specific badge sessions plugged in as well!

**Comment by Saallen** [comment]
@mattdigitalme I might leave off the top paragraph but to expand on this in a blog post that we post directly to our audience. Would that be ok with you?

**Comment by Saallen** [comment]
@mattdigitalme can you please confirm the full list of all Wranglers names here to be added to the website? 
For 1st of June we are just adding names but will add Bios later in the fall

**Comment by mattdigitalme** [comment]
Sounds good to me - when you say all wranglers you mean DME staff right? Do they need GitHub handles?

**Comment by edrushka** [comment]
We don't need Github handles quite yet. Just names are good for now.

**Comment by mattdigitalme** [comment]
Ok sweet:

Definite:
Me (Matt Rogers)
Tim Riches
Lucy Lewis

Will confirm on Tuesday:
Grainne Hamilton
Sharon Ashley
Mark Riches
Kevin Field
Alison Booth
Katharine Courtney
Anna Sheard

**Comment by Saallen** [comment]
hi @mattdigitalme when I say Wrangler I mean the people who will be responsable for the entire work coming together and  showing up at MozFest-
Other roles within the Space are:
- Facilitators are those who lead a session or experience, 
- Pathfinders are those who designe a learning objective or path around a group of sessions or/and  experiences.

**Comment by Saallen** [comment]
@mattdigitalme I just wanted to confirm that you are building a series of session and experiences that fit under the learning hub of Badges, thus making you a Space. are you happy with running and Open Badges Space for MozFest?

**Comment by mattdigitalme** [comment]
Yup - well up for building a set of sessions! We've already got a few in mind we'll get partners to put proposals in for :) 

In terms of wranglers: it'll be me, Lucy, Tim and Grainne. Is 4 ok?
