### ISSUE TITLE
Space narrative- Localisation

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#38]
Copy shared as
*
The physical space ... To reflect the diversity of the world, a stage set like a market place with creative interesting textiles colours, flavours and smells.
*Be inspired, find out how people are adapting to the digital world and participating in building the Web in their own way reflecting their own unique culture and identity.
*Learn, building a community opening up your work to other languages and cultures .. let everyone translate everything. Open up the access doors. Talk to the localisation experts. The nuts and bolts from the developers of localisation tools.
*Pass it on, share your experiences in your own language - contribute something in your language. Keep your languages active and alive in the domains of today and the future.

**Comment by edrushka** [comment]
cc @KevZawacki

**Comment by Saallen** [comment]
As per @hjbailey request for a text remix I was going to take the first cut, cc @edrushka @kevin

We have created a Space to reflect the diversity of the world, a stage set like a market place with creative interesting textiles colours, flavours and smells. Here we want to create a community that spans many cultures and languages, a representitve force of those on the web.
We want to explore and find out how people are adapting to the digital world and participating in building the Web in their own way reflecting their own unique culture and identity. We can learn by opening up the access doors irrelevant of location, we want to offer space for the localisation experts to share their experiences and time for the developers  to share the nuts and bolts of localisation tools.
Come join us, share your experiences in your own language,  Keep your languages active and alive in the domains of today and the future.

**Comment by hjbailey** [comment]
Brilliant looking good.

**Comment by Saallen** [comment]
@hjbailey  can you please confirm the full list of all Wranglers names here to be added to the website? 
For 1st of June we are just adding names but will add Bios later in the fall

**Comment by hjbailey** [comment]
Heather Bailey
Dwayne Bailey
Manal Hassan

**Comment by edrushka** [comment]
@hjbailey We've edited all the Space Narratives for consistent copy and tone. How does this look to you for the final version?

**Localisation**
The Internet spans many cultures and languages — and so does the Localisation Space. 

This space reflects the diversity of the Web and the people who use it. It’s set up like a marketplace, rich with different colors, smells, and flavours. We’ll explore how people participate in the digital world in a way that reflects their unique culture and identity. Localisation experts and amateurs alike will share localisation tools, discuss their experiences on a multicultural Internet, and explore how we can create a Web that’s truly inclusive of all languages and societies.  

Have a great session idea? Head to the MozFest Call for Proposals page [link].
