### ISSUE TITLE
Space Narrative- Journalism

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#39]
Space narrative ready for @KevZawacki magic.
Looping in @erikao and @ryanpitts in case you have some questions

Journalism doesn't just tell the story of the internet, it's part of it. Software like Django, D3, and Backbone has emerged from newsrooms to power some of the most innovative work on the open web. Reporting entertains and challenges millions of readers every day, giving them the information they need to engage with their communities. 

In the Journalism Space, we explore how journalism can change our lives, both in person and online. Participants will learn how developers, designers, and data analysts collaborate to cover the most important stories of the day, and how they can contribute to the kind of work that protects the open web and drives it forward.

**Comment by Saallen** [comment]
@erikao confirming this is the Space title- Journalism

**Comment by Saallen** [comment]
@erikao can you please confirm the full list of all Wranglers names here to be added to the website? 
For 1st of June we are just adding names but will add Bios later in the fall

**Comment by edrushka** [comment]
@erikao @ryanpitts Here's your final Space Narrative (lightly edited for consistent copy and tone with the others).

**Journalism**
Journalism doesn't just tell the story of the Internet — it's part of it. Software like Django, D3, and Backbone has emerged from newsrooms to power some of the most innovative work on the open Web. And reporting entertains and challenges millions of readers online every day, giving them the information they need to engage with their communities.

In the Journalism Space, we explore how journalism can change our lives, both in person and online. Participants will learn how developers, designers, and data analysts collaborate to cover the most important stories of the day, and how they can contribute to the kind of work that protects the open Web and drives it forward.

Have a great session idea? Head to the MozFest Call for Proposals page [link].
