### ISSUE TITLE
Scope Landing page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#4]
Link to current page: https://2015.mozillafestival.org/

**What needs updating (by when):** 
**Asap**
- [x]  Mozilla 2016 Video 
- [x]  Swap Buy a ticket for Sign up for updates line
- [x]  Add dates for this years festival
- [x] Remove/hide from navigation until individual pages are updated in **May**
  - [ ] Tickets
  - [ ] Submission process
  - [ ] Fringe events
- [x] Remove/hide from bottom navigation until indivdiual pages are updated **September**
  - [ ] Schedule
  - [ ] Sessions
  - [ ] Remote

**Other thoughts/ideas**:
- [x] Update home page picture
- [ ]  Refresh order of navigational pages

**Comment by edrushka** [comment]
The ASAP changes have been filed in #19 and Mavis is working on them now. They should be done within the next week or two :)

We'll address the other thoughts/ideas when we meet with Willse and Jordan, and can plan to make those changes for the June 1 update.

**Comment by edrushka** [comment]
The ASAP changes have been done! Now scoping changes for the June 1 update.

**Comment by edrushka** [comment]
@Saallen - @vazquez has mocked up some new colour treatments and photos for the landing page: https://www.dropbox.com/sh/kmvm69tdgarwqm1/AADjDpNcMCjBumX7WPKmO215a?dl=0

I like 1 and 2. What are your thoughts?

**Comment by Saallen** [comment]
Ooh, loving the slight nod to Prince in the colour scheme @vazquez @edrushka 
I love the 2nd photo as ppl are smiling and there is a good mix of male to female. Amira obvs looks great but stage is such a small part of the 3 days that we shouldnt be calling it out on the main page. I love the idea of showing the science fair but with cool stuff on the tables- some of these tables look empty.

**Comment by vazquez** [comment]
My favourite photo is Number 2. Can we go for that one? 😃

**Comment by Saallen** [comment]
:+1:

**Comment by edrushka** [comment]
@Saallen @KevZawacki @omnignorant 
Here's a first pass at copy updates for the MozFest site landing page. Does this feel #mimi?

1) For the main text over the image: 

MozFest
October 28-30, 2016
Ravensbourne, London
The world’s leading event for and by the open Internet movement.
Join us to build, debate, and explore the future of our lives online.

2) For the CTA banner:

Submit a session for MozFest 2016
We invite people from all fields: policy, science, journalism, arts and more. MozFest is for everyone, regardless of your gender, geography, age or language.

**Comment by KevZawacki** [comment]
@edrushka 👍 I really like having this language on the homepage.

Maybe we add "technology" as a field?

**Comment by vazquez** [comment]
In case you want a visual:

![screen shot 2016-05-18 at 9 56 45 am](https://cloud.githubusercontent.com/assets/1119821/15361297/de2d7582-1cde-11e6-885d-8b1b6e14aeb9.png)

**Comment by Saallen** [comment]
👍

**Comment by vazquez** [comment]
Perfect, I will push this change ~~when the Proposal page is finished.~~ now since we are only updating the staging site.

**Comment by vazquez** [comment]
I think this issue is good to close! All changes are now in staging environment.

**Comment by edrushka** [comment]
Boom! 💥
