### ISSUE TITLE
Space narrative- Fuel the Movement

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#40]
Space- Fuel the Movement
@KevZawacki @Melechuga @edrushka for input and copy editting if needed

Narrative:

Come fuel the open Internet movement! This year we’re focusing on Copyright. Mozilla believes intellectual property rights should foster innovation, creation and competition. We are looking for sessions to help participants understand how changes in copyright law could impact them.

Help raise awareness and shape the strategy to tackle the threats facing Copyright in the European Union. We also want to inject some fun and artistic creativity into the Internet policy and advocacy world! We envision our space as highly interactive and informative with a balance between workshops, lightning talks and collaborative making -- big experiences and small ones for participants to seamlessly learn, make, and collaborate. Artistic and creative design ideas -- including everything from DIY sign-making to IoT interventions  -- are strongly encouraged!

Festival participants will walk away energized and excited with a better understanding of present-day threats and what they can do to advocate for an Internet that puts people first. 

What are we looking for?
- Learning Labs (~60 min): Skill-share sessions that bring together people to learn from each other (e.g. best practices for community organizing).
- Hands-on workshop (1-3 hrs): Creative opportunities for people who wouldn’t normally collaborate around specific issues to build strategies and interventions. 
- Interactive exhibitions (no time limit; can be 5min experience, can be 2 days of making): Sessions that walk people through experiences, e.g DIY Snooper’s Charter photobooths, Virtual Reality experiences, etc. 
- Demo or Lightning talks (5-15 min): Product demos or issue-based lightning talks with Q&A (e.g. Copyright 101, Freedom of Panorama).

**Comment by Saallen** [comment]
Hi @KevZawacki @edrushka 
Thinking about the layout of the page, the other spaces texts and the lack of bullet points from other spaces. Could we remix Melissa request for different types of sessions as below?
I want to stay true to her text and specific call to action but we explain Learning labs. and workshops in the format question of the call so this info might be surplus text.
Could this call for specific types of sessions be remixed slightly as:
We are looking for a wide variety of creative opportunities for skill sharing, learning and ways to collaborate, such as learning labs, hands on workshops,  demo or lightening talks. This year we are also interested in hear from interative exhibitions which have no time limits and can span over the two days such as Privacy Car Wash, Scary Smart Home of the future (IoT), DIY Snooper’s Charter photobooths, Virtual Reality, etc.

**Comment by KevZawacki** [comment]
Hi @Saallen, no problem :-)

**Comment by Melechuga** [comment]
Space name: Fuel the Movement

**Comment by Saallen** [comment]
🔥

**Comment by Saallen** [comment]
@Melechuga can you please confirm the full list of all Wranglers names here to be added to the website?  For 1st of June we are just adding names but will add Bios later in the fall

**Comment by Melechuga** [comment]
Wranglers: Stacy, Raegan, Georgia (and me).

**Comment by Melechuga** [comment]
@Saallen @KevZawacki I've updated the narrative above; we've narrowed our scope around Copyright to align with internal strategy.

**Comment by edrushka** [comment]
@Melechuga We've edited all the Space Narratives for consistent copy, tone and wordcount. I'm including a screenshot from the Call for Proposals form to show how we're asking for different types of sessions. Let me know if the edits to your narrative are ok.
![screenshot 2016-05-27 15 40 42](https://cloud.githubusercontent.com/assets/4515662/15622802/96810a60-2421-11e6-995e-37920868d84a.png)

**Fuel The Movement**
The open Internet movement needs you! When everyday Internet users band together, we can overcome threats to the free and open Web and keep it a global public resource. 

In the Fuel The Movement Space, we couple fun and creativity with Internet policy and advocacy, specifically around the issue of copyright. Through interactive workshops, DIY making, and lightning talks, we’ll explore copyright in the European Union. Participants will walk away energized and equipped to stand up to present-day threats to the open Internet. 

Have a great session idea? Head to the MozFest Call for Proposals page [link]. Fuel The Internet Movement is searching for creative sessions like learning labs, hands-on workshops, demos, and interactive installations.

**Comment by Melechuga** [comment]
Awesome @edrushka! One thing -- can we add a little bit about the mission and less about the actual format (given that the format options are included in the larger form)? For example, can the paragraph say, 

"Mozilla believes intellectual property rights should foster innovation, creation and competition. We are looking for sessions to help participants understand how changes in copyright law in the European Union could impact them through interactive workshops, DIY making, and lightning talks. In the Fuel the Movement space, we couple fun and creativity with Internet policy and advocacy. Participants will walk away energized and equipped to stand up to present-day threats to the open Internet." 

Then we can get rid of the last line, and just end the narrative with "Have a great session idea?...go to the link." Thank you!

**Comment by edrushka** [comment]
@Melechuga How's this? I just changed "Mozilla believes" to "we believe", since spaces shouldn't feel too Moz-centric. 

**Fuel The Movement**
The open Internet movement needs you! When everyday Internet users band together, we can overcome threats to the free and open Web and keep it a global public resource.

We believe intellectual property rights should foster innovation, creation and competition. We are looking for sessions to help participants understand how changes in copyright law in the European Union could impact them through interactive workshops, DIY making, and lightning talks. In the Fuel the Movement Space, we couple fun and creativity with Internet policy and advocacy. Participants will walk away energized and equipped to stand up to present-day threats to the open Internet

Have a great session idea? Head to the MozFest Call for Proposals page [link].

**Comment by Melechuga** [comment]
@edrushka This is great! One last thing: change "open Web" to "open Internet" -- this is now the wording we're using, it seems. 

Thank you!!

**Comment by edrushka** [comment]
👍 done! Thanks Melissa.

**Comment by Melechuga** [comment]
We got some wording changes requested by the Policy team; how does the following sound @KevZawacki @edrushka @Saallen? Apologies for the back-and-forth!

**Fuel The Movement**
The open Internet movement needs you! When everyday Internet users band together, we can overcome the many threats to the free and open Internet, and keep it a global public resource.

This year, we're focusing on **copyright**. We believe copyright should foster innovation, creation and competition. Sessions should help participants understand how changes in copyright law in the European Union could impact them through interactive workshops, DIY making, and lightning talks. In the Fuel the Movement Space, we couple fun and creativity with Internet policy and advocacy. Participants will walk away energized and equipped to take advantage of present-day opportunities online.

Have a great session idea? Head to the MozFest Call for Proposals page [link].

**Comment by edrushka** [comment]
Whew...you made it just under the wire! Changes made!

**Comment by Melechuga** [comment]
You're the best @edrushka!! Really, REALLY appreciate it. Thank you.
