### ISSUE TITLE
Space narrative - Open Science

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#41]
Narrative for  Open Science Space
cc in @KevZawacki for some kevin magic
and @edrushka and @arlissc for any further clarity

Narrative

Science and the Web both help us understand the world around us. In the Open Science space, participants learn, remix, explore and hack at the intersection of science and the Internet, and learn how the Web can (/and is) transforming science.

We cover topics like open data, citizen science, open research, and science communication - all the while learning news skills and tools.  We also collaborate on each other’s projects and empower one another: our Open Research Accelerator provides one-on-one mentorship.

The Science Space is open to everyone: we invite hobbyists, researchers, librarians, data scientists, developers and all others to join us.

**Comment by Saallen** [comment]
@arlissc can you confirm the title for your Space?

**Comment by arlissc** [comment]
@Saallen - Name:  OPEN SCIENCE

**Comment by Saallen** [comment]
@arlissc  can you please confirm the full list of all Wranglers names here to be added to the website. For 1st of June we are just adding names but will add Bios later in the fall

**Comment by arlissc** [comment]
@Saallen - here you go.
Kirstie Whitaker
Joey Lee
Richard Smith-Unna
Arliss Collins :)

**Comment by edrushka** [comment]
Here's your final Space Narrative (lightly edited for consistent copy and tone with the others).

**Open Science**
Science and the Web both help us understand the world around us. In the Open Science Space, participants explore, remix, and hack at the intersection of science and the Internet, and learn how the Web is transforming research and discovery.

We cover topics like open data and research, citizen science, and science communication — all the while learning news skills and tools. We also collaborate on each other’s projects, and our Open Research Accelerator provides one-on-one mentorship for making your project open source. The Open Science Space is open to everyone: We invite hobbyists, researchers, librarians, data scientists, developers, and all others to join us.

Have a great session idea? Head to the MozFest Call for Proposals page [link].
