### ISSUE TITLE
Space narrative : Demystify the web

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#42]
Space: Demystify the web
Space Wrangler : @omnignorant 
cc @KevZawacki & @edrushka 

Grab your ticket to our carnival of learning! All who enter will gain the most important skills of our age: the ability to read, write and participate in our digital world. Mozilla Learning invites teachers and learners of all ages to join our funhouse of web literacy. Embrace the unknown! Experience the thrills! Imagine and share the full potential of the web with everyone!

We’re looking for proposals that share fun, interactive ways to teach and learn the web in diverse, inclusive spaces; proposals designed for creative collisions; proposals that inspire people to engage in an openly networked world.

**Comment by Saallen** [comment]
@omnignorant can you please confirm the full list of all Wranglers names here to be added to the website. For 1st of June we are just adding names but will add Bios later in the fall

**Comment by omnignorant** [comment]
@Saallen when you say "Names" are you actually asking for email or GitHub handles, or just first/last name?
- Kim Wilkens
- Su Adams
- Simeon Oriko

**Comment by edrushka** [comment]
Names are good for now. Thanks, Robert!
