### ISSUE TITLE
Call for Proposals in Arabic

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#44]
Thanks to @hjbailey and some other amazing folks we now have our call for proposals form in Arabic
If you have any questions please direct them to heather esp for the final nod once we are ready to push live. CC @edrushka
Form:
https://docs.google.com/a/mozillafoundation.org/forms/d/1HoI1l8xRXnKyOW83QSvyG6knKZ2bNnDjMyES2U9lkB8/edit

**Comment by edrushka** [comment]
cc @ScottDowne

**Comment by Saallen** [comment]
@hjbailey there have been changes to Space names and new ones added. Can someone form your team make amendments for us?
In section one the list of spaces should be
*Digital Arts and culture
*Localisation
*Open science
*Journalism
*Moz Ex (art exhibit)
*A Tale of Two Cities: Dilemmas in Connected Spaces
*Demystify the web
*Open badges
*Youth Zone
*Fuel the movement

Section two should have 
*Digital Arts and culture
*Localisation
*Open science
*Journalism
*A Tale of Two Cities: Dilemmas in Connected Spaces
*Demystify the web
*Open badges
*Youth Zone
*Fuel the movement
- No

Section three should have
*Digital Arts and culture
*Localisation
*Open science
*Journalism
*Moz Ex (art exhibit)
*A Tale of Two Cities: Dilemmas in Connected Spaces
*Demystify the web
*Open badges
*Youth Zone
*Fuel the movement
*No
