### ISSUE TITLE
Space narrative: A Tale of Two Cities: Dilemmas in Connected Spaces

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#46]
Space Narrative- A Tale of Two Cities: Dilemmas in Connected Spaces
Space Wranglers : cc @thornet @ileddigital @cubicgarden @autonome @geroter 
cc @edrushka @KevZawacki 

Narrative:
As our lives and physical environments become even more connected, we're faced with dilemmas. Should I allow my personal data to be used if it improves my daily life? Should my everyday objects be online? If my profession calls for me to make connected products or services, how should I balance user agency with seamless experience?

This space will allow makers and learners to explore these dilemmas through a series of interactive experiences and mischievous interventions. Think connected and disconnected, public and private, privileged and disadvantaged, inclusive or exclusionary. 

Participants might:
- Arrive in a disorienting immigration queue like at an airport and make decisions about their identity and what they will declare...
- Join a tour as seen through the eyes of dead scientists and poets. 
- Have a tea in a temporary camp and chat to nomadic algorithms. 
- Nap on a squishy chair sculpture that generates sleep data. 
- Cook a snack in a connected kitchen where appliances will only sometimes do as you say.
- Hop on the gondola and learn magic tricks as you travel above the Thames.
- Dig into oh-so-cool hardware to make and break the garage. 
- Stroll through a secret garden and see if you can make it out again...

We're seeking fellow pranksters who want to create these kinds of memorable moments. 

We're less interested in sessions and more interested in experiences: dance-offs, exhibits, interactive comic books, newly invented sports, crazy sets and drama of all kinds.  

In the call for proposals, we invite you to describe how you would make these tales come to life, or share you suggestions for new ones.

**Comment by edrushka** [comment]
@thornet @ileddigital @cubicgarden @autonome @geroter We've edited all the Space Narratives for consistency in copy, tone, wordcount and format. Does this work for you as your final Space Narrative? 

**A Tale of Two Cities: Dilemmas in Connected Spaces** 
As our lives and physical environments become even more connected online, we're faced with dilemmas. Should I allow my personal data to be used if it improves my daily life? Should my everyday objects be online?

This space will allow makers and learners to explore these dilemmas through a series of interactive experiences and mischievous interventions. Participants might nap on a squishy chair that generates sleep data; cook a snack in a connected kitchen where appliances only sometimes do as you say; and hack on IoT hardware.

Have a great session idea? Head to the MozFest Call for Proposals page [link]. We're seeking fellow pranksters who want to create memorable moments. We're less interested in traditional sessions and more interested in experiences like dance-offs, exhibits, interactive comic books, and newly-invented sports.
