### ISSUE TITLE
Set up confirmation email for session proposals

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#47]
After people submit their MozFest session proposal via the website (this work tracked in #16), we need to send them a confirmation email (copy has been finalized in #28).

@ScottDowne is taking care of the form, and getting the data transferred from the Google Spreadsheet to Github. @cadecairos, can you pick it up from there? The tricky bit is getting each person's custom github ticket into the email.

The Call for Proposals goes live on June 1. We can extend the deadline on the email confirmation slightly, but **firm deadline is June 8**.

**Comment by edrushka** [comment]
cc @simonwex

**Comment by cadecairos** [comment]
We're cutting it a bit close here.

A few questions: (for either @edrushka or @ScottDowne)
1. What email address are we sending confirmations from? Depending on which, and were we send it we'll need to confirm domain ownership if we havent sent from that provider before.
2. Do we want to send emails using an existing system set up for transactional email? (sawmill/lumberyard, which does login and donate emails right now) or via some other means?
3. It sounds like whatever is moving data from a spreadsheet to github is the right place to trigger the email render/send process, since the github API should tell us what Issue number is assigned to something it creates. Does this sound right?

**Comment by ScottDowne** [comment]
I can answer 2 and 3. It'll be using sawmill and etc. And yeah the code
that sends it is going to be the code that syncs with github which is on my
end. I just need sawmill setup to know how to send this email when I ask it
to.

**Comment by Saallen** [comment]
Can we send the confirmations from festival@mozilla.org 
as this is where we direct folks if they have any questions so for consistancy this would be my preferance

**Comment by cadecairos** [comment]
@Saallen Do you have access to this email address' inbox? I'm going to need to verify it for sending emails.

**Comment by cadecairos** [comment]
looks like we'll have to go through Moco to get this working. I'm not sure how long that will take.

**Comment by ScottDowne** [comment]
Possible by June 1st-3rd?

**Comment by cadecairos** [comment]
that depends on how comfy they are with letting our AWS account send mail from any mozilla.org address. I'm filing an IT bug to see.

**Comment by cadecairos** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1276205

**Comment by ScottDowne** [comment]
@cade Looking at last year's code, we have this block:

```
      hatchet.send("mozfest_session_proposal", {
        email: email
      }, function(err, data) {
        if (err) {
          console.error("Error sending email: " + err);
        } else {
          console.log("we sent a message!");
        }
      });
```

Looks like we're already capable of this.

**Comment by cade** [comment]
I'm hesitant to weigh in on the viability of your code suggestion, @ScottDowne, until I'm able to compare it to the bug ticket that @cadecairos has created. Unfortunately, when I click the link, it says "Access Denied". Please give me access to all the things so I can give you a fully informed opinion.

In the mean time, would it help to add a few `iframe`s?

**Comment by ScottDowne** [comment]
@cade lol!

I  :heart: `iframe`s

**Comment by edrushka** [comment]
@cade is such a good sport! 🙇

**Comment by ScottDowne** [comment]
@edrushka ok cool, looks like we'll probably be able to do this.

The email body we used last year was:

```
Thank you for submitting your proposal for Mozfest 2015.

The list of selected proposals will be announced in September. Until then, keep up to date with festival news here: http://mozillafestival.org/

If you have questions about your submission, please email us at <a href="mailto:festival@mozilla.org">festival@mozilla.org</a> You can also tweet us at @Mozillafestival using #MozFest.

Good Luck!
```

We just need to update it.

**Comment by edrushka** [comment]
@cadecairos - hoping for updates on a couple things:
1) any word from MoCo on sending emails from festival@mozilla.org
2) will we be able to include a unique github link in the email?

**Comment by ScottDowne** [comment]
@edrushka no to the github integration, haven't even started. If it means we shouldn't send out any emails until we have github integration, then we can continue to put a pause on the email for now.

**Comment by edrushka** [comment]
My question is will the GH integration be possible? If not, we can go to plan B.

**Comment by cadecairos** [comment]
> 1) any word from MoCo on sending emails from festival@mozilla.org

I think we may already be set up to do this from last year, will confirm.

**Comment by mmmavis** [comment]
THIS IS DONE 🎉 THANKS TEAM

try submitting a proposal via https://mozillafestival.org/proposals if you are curious 😉 

👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯

**Comment by cade** [comment]
![yusss](https://cloud.githubusercontent.com/assets/3403/15910432/67ddf42a-2d90-11e6-9516-629545c65070.gif)

**Comment by cadecairos** [comment]
One of us is going to have to start going by something other than cade - Rock Paper Scissors? :laughing:

**Comment by cade** [comment]
![rps](https://cloud.githubusercontent.com/assets/3403/15910816/4fdde504-2d92-11e6-8853-7a18afb422fd.gif)

(My apologies to anyone who may be trying to actually get work done...)

**Comment by edrushka** [comment]
I think @cade should just come work for Mozilla. Clearly he's one of us.

https://careers.mozilla.org/listings/

**Comment by mmmavis** [comment]
> I think @cade should just come work for Mozilla. Clearly he's one of us.
> https://careers.mozilla.org/listings/

👍 👍 👍 👍 👍

**Comment by cade** [comment]
If I didn't like my current job so much, I would never stop telling the story of how I gif'd my way into a job at Mozilla on the back of @cadecairos's GitHub handle.

It'd be funny at first, but then when you realize I'm just going to keep telling the story, you'd be all, "Dear eight pound, six ounce, newborn baby Jesus, in your golden, fleece diapers, with your curled-up, fat, balled-up little fists pawin' at the air, _WHY DID WE HIRE THIS CRAZY PERSON?!_"

I mean, **I** wouldn't mind. I'm just looking out for you...
