### ISSUE TITLE
Github integration- labelling

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#49]
Hi @ScottDowne @mmmavis @edrushka 
I wondered if y'all had a separate conversation on about github integration and labelling?
In previous years we used Milestones to indicate acceptance of session and labels for pathways.

Since this year submissions are able to pick two Spaces they would like to accepted under how will this show up on the intragation from google form to github? 
Are we using milestone for first choice space and label for second choice- or just both spaces are indicated with a label and milestones are allocated during curation ??

**Comment by edrushka** [comment]
@mmmavis what do you think is the best technical solution? Could we make labels that say Alt:YouthZone (or whatever the alternate space is)? If not, could the alternate space be part of the information that's ported over to the Github comment?

**Comment by mmmavis** [comment]
(correct me if I'm wrong plz @edrushka @Saallen )

From our discussion earlier today (re: https://public.etherpad-mozilla.org/p/festival-sessioncuration) we will assign both Space labels to the ticket. We will also mention which Space is being the 1st choice & what is being the 2nd choice Space in the ticket.

So for example, my session proposal has `Journalism` as 1st choice Space and `Youth Zone` as backup. When imported into Github the ticket will have `Journalism` and `Youth Zone` Space labels assigned to it. In the ticket description we will mention `Journalism` being the 1st choice Space and `Youth Zone` being the 2nd choice.

**Comment by mmmavis** [comment]
Done. See sample GitHub ticket: https://github.com/MozillaFoundation/mozfest-program-2016/issues/1 💐
