### ISSUE TITLE
Proper links to translated forms

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#50]
The forms are here, but these are the editable links. For the life of me I can't get public, non-editable links to these. Maybe one of you will have more luck @Saallen @ScottDowne 

French
Spanish: https://docs.google.com/a/mozillafoundation.org/forms/d/1uoZArtKcmY9v4bl8mcS7smMI-HhkuIW6zXlscUpYMds/edit
Arabic: https://docs.google.com/a/mozillafoundation.org/forms/d/1HoI1l8xRXnKyOW83QSvyG6knKZ2bNnDjMyES2U9lkB8/edit
French: https://docs.google.com/a/mozillafoundation.org/forms/d/1Pv4bMrSXhhUuxR426XxWYlLfjBsIExJrldpOfzYLcMM/edit

**Comment by ScottDowne** [comment]
I think these are the usable links
spanish https://docs.google.com/forms/d/1uoZArtKcmY9v4bl8mcS7smMI-HhkuIW6zXlscUpYMds/viewform
arabic https://docs.google.com/forms/d/1HoI1l8xRXnKyOW83QSvyG6knKZ2bNnDjMyES2U9lkB8/viewform
french https://docs.google.com/forms/d/1Pv4bMrSXhhUuxR426XxWYlLfjBsIExJrldpOfzYLcMM/viewform

I think it's the little eye icon in the top right.

**Comment by Saallen** [comment]
Let me know if you continue to have trouble with this links
I have made them into cute bit.ly links 🐤 
http://mzl.la/Français
http://mzl.la/MozFestArabic
http://bit.ly/MozFestSpanish

**Comment by ScottDowne** [comment]
Done! https://arcane-peak-71038.herokuapp.com/proposals
