### ISSUE TITLE
Updates- should the link still be live

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#51]
Once we start to sell tickets should there be a link somewhere where people can continue to request updates about the festival?

**Comment by Saallen** [comment]
Thanks for adding the stay in contact page- i did notice that when I click on the stay in contact page I see this :https://ti.to/Mozilla/mozfest-2016
Both tickets and Update sign up
Does anyone know if the ticket page is linked directly to the tickets themselves? so if I turn off the link between tickets and mozilla ti.to home page I wont break anything? @vazquez  or @mmmavis or @ScottDowne ??

**Comment by ScottDowne** [comment]
I'm not following but I'll be in the office in ten mins and I'll ping you :)

**Comment by Saallen** [comment]
No rush= ping me when ready as i think it will be best of I share screen with you to explain as noticed another little bug

**Comment by Saallen** [comment]
Update: There is a little :bug: linking the 2016 tickets with the ticket page. @ScottDowne is working on it and rating the ti.to support team as I type.

Another issue but not a  MVP but something I will try fix if that the updates link leads to the ti.to mozfest home page which displays all tickets as well and the sign up for updates link. It would be awesome if just the sign up was here....

**Comment by ScottDowne** [comment]
the updates for the tickets are in a patch here which is one @mmmavis for review.

https://github.com/mozilla/mozillafestival.org/pull/390

The bug with this is that  locally it doesn't use the widget, it just links. I'm assured by tito that when it's live, and on https, it'll use the widget. So nothing needs to happen to fix that part of the linking bug, we just need to point the widget to the 2016 tickets and we'll be good to go.

**Comment by Saallen** [comment]
Hey @ScottDowne  did we point the widget to the 2016 tickets?

**Comment by ScottDowne** [comment]
@Saallen we did, but I think it still needs to be pushed to production.

I'm not familiar with how to do that on mozfest currently. cc @mmmavis?

**Comment by mmmavis** [comment]
@ScottDowne merging to `develop` (and `master`) auto triggers the build 🌞

**Comment by mmmavis** [comment]
It will take a while for the changes to show on https://mozillafestival.org (due to CDN)

**Comment by mmmavis** [comment]
I believe we can close this ticket now 😉
