### ISSUE TITLE
Fields to be integrated into program github

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#52]
These are the fields from the Call for Proposals to be integrated into the top comment of the each issue
List of fields to be integrated into the first comment on Github cc @edrushka 
- First name
- Surname
- Organisation
- Twitter
- Space
  - this also gets a github label
- Title of piece- should be the Issue title if filled in
- Method: 
- Link to see your work:
- Description 
- Format
- Session title- should be the Issue title if filled in
- Decription
- Agenda
- Participants
- Outcome
- Secondary space
  - this also gets a github label

@mmmavis    If a field is left blank is there a way not to have the field referenced on the issue?

**Comment by mmmavis** [comment]
@Saallen 

> @mmmavis    If a field is left blank is there a way not to have the field referenced on the issue?

yup yup

**Comment by mmmavis** [comment]
Hey @Saallen what did you mean by "agenda"? Which question on the form is it linked to?

**Comment by Saallen** [comment]
@mmmavis  Agenda -How do you see that working?

**Comment by mmmavis** [comment]
Hi @Saallen and @edrushka 

Could you try submitting proposal on my build: http://mavis-mozfest.herokuapp.com/proposals and see if GitHub issue get filed as expected? https://github.com/mmmavis/test-mozfest-2016-proposals/issues (my test mozfest proposal repo) 🌞

**Comment by edrushka** [comment]
@mmmavis I submitted something

**Comment by mmmavis** [comment]
Hello @edrushka and @Saallen 😄 could you verify that the exported GitHub ticket is in the format & contains all the information we want?

**Comment by mmmavis** [comment]
@Saallen ^

**Comment by Saallen** [comment]
Hey @mmmavis , it looks like  you are just missing
*outcomes

which is the question on section3 :What do you see as outcomes after the festival? How will you and your participants take the learning and activities forward?

**Comment by mmmavis** [comment]
@Saallen nice catch! thanks! I fixed that issue. Gonna ask Scott to review my PR now. 🌞

**Comment by mmmavis** [comment]
Done 🚀 🎉 See my test proposal on the program repo here: https://github.com/MozillaFoundation/mozfest-program-2016/issues/4

👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯 👯

**Comment by Saallen** [comment]
Great work @mmmavis Thank you!!!! ⭐

**Comment by mmmavis** [comment]
❤️
