### ISSUE TITLE
Space names for Github label

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#53]
Please make these titles in Github labels @mmmavis 🔬 

Digital arts and culture
Localisation
Open science
Journalism
Moz Ex 
A tale of two cities: a dilemma of connected spaces
Demystify the web
Open badges
Youth zone
Fuel the movement

**Comment by mmmavis** [comment]
Yup yup I can do that. We'll need to add a prefix to these Space labels. What do you think about adding `[Space]` to them? @Saallen 

e.g., 
`[Space] Digital arts and culture`
`[Space] Localisation`

**Comment by mmmavis** [comment]
Also, is this the repo where the proposals are gonna live? https://github.com/MozillaFoundation/mozfest-program-2016

**Comment by Saallen** [comment]
Yes, thats a good idea @mmmavis all are spaces except Moz Ex- which is an experience
so will need [ Experience ] Moz Ex
Yes that is the repo

**Comment by mmmavis** [comment]
DONE! https://github.com/MozillaFoundation/mozfest-program-2016/labels 💃
