### ISSUE TITLE
Security Error on Page Load at mozillafestival.org

### ISSUE THREAD

**Issue by omnignorant** [MozillaFoundation/2016.Mozillafestival.org#54]
Not sure what this is about, but see screenshot:

> Your connection is not secure
> The owner of mozillafestival.org has configured their website improperly.

![screen shot 2016-06-03 at 8 06 23 am](https://cloud.githubusercontent.com/assets/6335874/15779500/5a390bca-2962-11e6-9ec0-7f0c3bb21bdc.png)

**Comment by Saallen** [comment]
Thanks @omnignorant All fixed now 👍
