### ISSUE TITLE
Accessing the website : Website not secure!

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#55]
![screen shot 2016-06-03 at 15 44 51](https://cloud.githubusercontent.com/assets/10194015/15782430/32b8b1e6-29a2-11e6-8779-62074e680c2a.png)

**Comment by Saallen** [comment]
CC @mmmavis  CC @edrushka

**Comment by ScottDowne** [comment]
@cadecairos ^^
