### ISSUE TITLE
Fix Ti.to integration

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#56]
The Ti.to ticket sales seem to be pointing to 2015 (which is now closed for sales). Can we get ticket sales live for 2016 please?

@mmmavis please prioritize this over the Github integration pieces as we can't publicize the site until this is fixed. Thanks! 🐴 

cc @Saallen and @ScottDowne

**Comment by mmmavis** [comment]
kk doing the push now. it's on staging already but i forgot to push it to production. 😉

**Comment by edrushka** [comment]
Woot! It works now! Thanks for doing that so quick 🏇 

I noticed that we're using draft copy on the ticket description but unfortunately I can't find the updated copy. _This is not a blocker - we can simply update the text next week_ @Saallen where's the ti.to copy we hacked?

**Comment by Saallen** [comment]
@edrushka , there is two sections to the ticket copy- what we have on the mozfest website as seen. 
Then what is linked directly to the ticket page- as below
Join us for three days to build, debate and explore our lives online. This ticket gains you entry to the festival from Friday night at 18:00 for the Science Fair and two days of sessions, workshops and talks taking place all day Saturday and Sunday. This ticket will also cover great coffee, lunch on Saturday, Sunday and adult beverages! Plus swag, an after party, demos and so much other great stuff that we cannot fit here

**Comment by Saallen** [comment]
Is there a way to get the prices of tickets on the mozfest webpage?

**Comment by edrushka** [comment]
@Saallen we edited that text to make it, and the youth text, more aligned. I thought we did the edits on a GDoc but I can't find it now. Maybe we did them directly in Ti.to?

I'll file a new ticket to get the prices on the MozFest page.
