### ISSUE TITLE
Show ticket price on ticket page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#57]
Can we adjust the text in the Youth and Adult ticket description text on the [Tickets page](https://mozillafestival.org/tickets) to show the prices?

Youth Ticket £3

Adult Ticket £45

Is this good @Saallen or do you want it on the actual ticket graphic?

**Comment by Saallen** [comment]
@edrushka its good just having the price beside the ticket name and description- thanks

**Comment by mmmavis** [comment]
DONE! https://mozillafestival.org/tickets 👯 👯

**Comment by Saallen** [comment]
Thanks @mmmavis 🎆
