### ISSUE TITLE
Bug- Wranglers on Open Badges

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#58]
Page: https://mozillafestival.org/spaces-and-sessions
Space: Open badges

Bug- Lucy Neale should be Lucy Lewis (my bad)
Can you add Grainne Hamilton

CC @edrushka @mmmavis

**Comment by Saallen** [comment]
Bug 🐛 
Page: https://mozillafestival.org/spaces-and-sessions
Experience (space page) Moz eX
Please add additional wrangler: Irini Papadimitriou

**Comment by Saallen** [comment]
Bug 🐛 
Page: https://mozillafestival.org/proposals
Intro paragraph- This year we are also accepting proposals in Spanish, French and Arabic.

Please add also into the line as it is currently missing 🙇

**Comment by mmmavis** [comment]
DONE!

**Comment by Saallen** [comment]
whoop
