### ISSUE TITLE
Making ti.to emails fancy

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#59]
I want to use TI.TO to send my festival correspondance but the emails are pretty plain. 
https://ti.to/Mozilla/mozfest-2016/admin/messages/dash
I know Ricardo made the event page look pretty but is there a way to make the embedded email look puurty? @mmmavis do you know?
cc @edrushka

**Comment by mmmavis** [comment]
hey @Saallen I don't see any advanced options here: https://ti.to/Mozilla/mozfest-2016/admin/settings/emails 😞

**Comment by Saallen** [comment]
Its gravy- I added the logo directly into the email. 🌴
