### ISSUE TITLE
Scope Location page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#6]
Link to current page: https://2015.mozillafestival.org/location

**What needs updating October:** 
- [ ] Update content for 2016
- [ ] Freshen page

**Other thoughts/ideas**:
- [ ] Move to bottom navigational bar

**Comment by edrushka** [comment]
@Saallen suggested copy change for this page:

MozFest Venue
Mozfest 2016 will be held once again in Ravensbourne, a media campus in the heart of London. Located right next to the O2 arena and North Greenwich tube station, Ravensbourne's nine floors of open work spaces, breakout rooms and cozy corners are ideal for collaboration and creative working.

**Comment by Saallen** [comment]
👍

**Comment by edrushka** [comment]
@vazquez only copy change on this page is 

MozFest Venue
Mozfest 2016 will be held once again in Ravensbourne, a media campus in the heart of London. Located right next to the O2 arena and North Greenwich tube station, Ravensbourne's nine floors of open work spaces, breakout rooms and cozy corners are ideal for collaboration and creative working.

However, could you look into fixing the map, so when you land on the page and try to scroll down, it actually scrolls down and doesn't resize the map? This drives me insane!

**Comment by vazquez** [comment]
That's a perpetual problem with embedding maps :( I will change the copy for now and talk to scott about preventing interaction with the map.

**Comment by vazquez** [comment]
Creating new issue for the map.
