### ISSUE TITLE
Session submissions in a different language

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#60]
Hi @mmmavis 
Is it possible to get the spanish, Arabic and French session submitted and ported to github the same as the main proposals form but with the additional label of the actual language?
For example [Spanish] [French] [Arabic]

cc @edrushka

**Comment by mmmavis** [comment]
Hey @Saallen 

Unfortunately for sessions that are NOT submitted via https://mozillafestival.org/proposals we will have to manually enter those into GitHub. [I'll add a issue template to the program repo](https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/61).

**Comment by mmmavis** [comment]
note that we'll have to manually email those people too

**Comment by Saallen** [comment]
OK! Cool- I can take on that of entering those sessions as they come in. I will need to think of a plan on how to email them sucessfully.

**Comment by mmmavis** [comment]
@Saallen I'm working on instructions and markdown template for you to reference: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/61 Will let you know once it's done!

Could we make sure these manual ticket entries are given a special GitHub label? It's likely we'll have to massage the values a bit to make sure they match what we set up for the proposals submitted via the MozFest site. And a GitHub label can help a lot with filtering! 😉

**Comment by Saallen** [comment]
Sure, what are you thinking of as a word to highlight these? I was going to label them with the spaces but also the language they are submitted in as the localisation team .

**Comment by mmmavis** [comment]
@Saallen is the deadline for submitting proposal early August? Will there be more proposals coming in after we take down the form from the MozFest site?

**Comment by Saallen** [comment]
Helloooooo @mmmavis  🍊 
We will be closing this form on 18:00pm PST Monday the 1st of Aug- 
I can ask @marcwalsh  to coordinate.

**Comment by marcwalsh-zz** [comment]
Hey @mmmavis 

There will still be some more coming in after the 1st from our partners etc. It would be good to leave the form live if possible as it makes it a lot easier for me when I'm adding in other languages and just remove links to the form from the website.

**Comment by edrushka** [comment]
@mmmavis Marc or I will file a couple tickets for you on this. One to change the 'submit a proposal' cta from the site, and the second to change the link of the form (keeping it live) so our partners can add last-minute sessions over the next week or two.

**Comment by mmmavis** [comment]
@marcwalsh @edrushka okie dokie! 

Just a note - for proposals submitted directly using the Google form (vs via MozFest site) they won't automatically show up on the [2016 program repo](https://github.com/MozillaFoundation/mozfest-program-2016). We'll have to either manually enter them in (I will provide instructions) OR write a different script to do the job for us.

**Comment by Saallen** [comment]
poop! @mmmavis would you be against people addin them  directly to github with a template?

**Comment by edrushka** [comment]
Confirming that the schedule app will populate from the spreadsheet and not GH, correct? I feel very nervous about letting people manually enter data that we'll need for the schedule to display properly.

**Comment by mmmavis** [comment]
@Saallen @edrushka 🌻 

Adding proposals directly to Github is probably not a good idea. Spreadsheet should always be the primary source of data... and it can protect personal data as well.

I'd say after August 1st we ask our partners etc to submit proposals using the Google Form (not via MozFest site). We can decide how we want to file Github tickets for those proposals submitted after Aug 1st (as well as proposals in other languages). Depends on the volume of these proposals, we can 1) manually enter Github tickets 2) OR I can write a script that batch export them to Github

**Comment by edrushka** [comment]
Sounds good. If any manual entry has to be done, I'd prefer it'd be done by us. A batch export script sounds ideal, though. Maybe we could run it every day or two for the first week, and then weekly?

**Comment by Saallen** [comment]
Hey
I imagine the bulk will be in the first two weeks, then it will defo pitter
off. So Batch export script would be great to help here if possible

Sarah Allen

Events Manager and Mozilla Festival Producer
Mozilla Foundation

Find out more about MozFest https://mozillafestival.org/ and follow the
conversation on twitter https://twitter.com/mozillafestival?lang=en-gb

**Comment by edrushka** [comment]
Ticket has been filed here:

Change URL for submission form #74

Let's continue any conversations there. I'm going to close this one for now, as it was originally about something else.
