### ISSUE TITLE
Plan for proposal submitted before GitHub integration was in place

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/2016.Mozillafestival.org#62]
- [x] @mmmavis to enter those proposals to https://github.com/MozillaFoundation/mozfest-program-2016
- [x] @mmmavis to prepare Google Spreadsheet that contains info needed for @cadecairos to send out confirmation emails to those proposal submitters
- [x] @cadecairos to send out emails

anything else?

/cc @edrushka @Saallen

**Comment by edrushka** [comment]
Sounds good. Hopefully there's not too many sessions.

**Comment by mmmavis** [comment]
11 GitHub tickets have been manually entered: https://github.com/MozillaFoundation/mozfest-program-2016/issues. @cadecairos I've created & shared a spreadsheet with you (check your inbox for invitation 😉)

**Comment by cadecairos** [comment]
@mmmavis All 11 emails have been sent!

:tada:

**Comment by cadecairos** [comment]
For future reference, this was easy to do using this simple script: https://gist.github.com/cadecairos/f6999c51f6cbe81d7fd8500847dc046d

I took the data in the spreadsheet, modified the column titles to match the expected inputs for the email template, converted it to JSON and ran it through that script (with all the right ENV secrets in place)

**Comment by mmmavis** [comment]
RAD 👍 🎉 🚀

**Comment by edrushka** [comment]
You two are the best. THANK YOU!
