### ISSUE TITLE
Copy help on issue template on mozfest-program-2016

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/2016.Mozillafestival.org#63]
Hey @edrushka , to prevent people from entering proposals directly to the `mozfest-program-2016` repo I'm thinking about adding `ISSUE_TEMPLATE.md` there. Content we put in `ISSUE_TEMPLATE.md` will show up in the description portion on the [new ticket page](https://github.com/MozillaFoundation/mozfest-program-2016/issues/new).  Can I get some help on the copy? I think we should encourage people to use https://mozillafestival.org/proposals ! 🌟

**Comment by edrushka** [comment]
Good idea! It didn't occur to me that people might directly add sessions to Github. For copy, how about:

Please do not submit session proposals directly through Github. Instead, submit your session through the [Call For Proposals form](https://mozillafestival.org/proposals).

If you submit your session directly though Github it will not receive the unique identifiers required for the curation process and inclusion in the final schedule. 

Thanks,
The MozFest Team

^ @Saallen how's that?

**Comment by Saallen** [comment]
Beauuuutiful 🐻

**Comment by mmmavis** [comment]
DONE
