### ISSUE TITLE
Image and text for Mobile site

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#64]
Hey @mmmavis & @edrushka 
I gave our URL to a friend today for testing with a beacon on a mobile.
When I shared the mozillafestival.org URL the picture that comes up is the 2015 cover with " arrive with an idea leave with a community. The year is correct as seen from the image
![magnet](https://cloud.githubusercontent.com/assets/10194015/16008419/d752424c-316f-11e6-99be-5b68ba541268.png)

Can we update this to the 2016 image and text?

**Comment by mmmavis** [comment]
nice catch! working on the fix now 🚀

**Comment by mmmavis** [comment]
Fix is in! Will take a while for it to update on the Webbb
