### ISSUE TITLE
2015 website home page

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#67]
Hey @edrushka 
The home page for 2015 says " 2016 dates coming soon" can we get this updated with prehapes a link to the this years website-
It could be best to let this website exist on its own and make no reference to 2016- as per older versions of the site

**Comment by Saallen** [comment]
![screen shot 2016-06-30 at 11 19 54](https://cloud.githubusercontent.com/assets/10194015/16485088/d6805fc8-3eb4-11e6-80ea-26144a8dc701.png)

**Comment by edrushka** [comment]
The 2015 site now redirects to 2016 as discussed in https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/69#issuecomment-235343949 so no one should be seeing it anymore.
