### ISSUE TITLE
Moz Ex- sharing the call

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#68]
Hey @mmmavis and @edrushka 

The Tate and the VnA are having difficulties sharing their calls on their websites-
This is their issue
"However, we also would like to put something up on the Tate website to help us push the call and make it more open - we are struggling to link to the MozFest call, mainly because it is not very clear what MozEx is when you go straight to the Submission page on the MozFest site. It would be great to have a link that goes straight to the Space-description for Moz Ex (anchored link) is possible - or perhaps a menu of spaces at the top of the page so that people know the spaces available without having to scroll all the way down. Is that possible?"

I know we cannot make edits to the website but is there a way to facilitate this request in another shape?
I was wondering if it was possible to give them a link that leads straight to the Moz Ex page- i know this means losing the facilitators name etc? 
Is the solution to make another form for them but I dont like diluting the submission process?

Any ideas, thoughts and solutions most welcome 😟

**Comment by edrushka** [comment]
Hmmm....losing all the info from the first page of the form seems like a decision that could bite us in the butt later. 

I'd prefer creating a one-page form for them if we can export the data into the spreadsheet/github process without breaking the current system.

@mmmavis what do you think?

**Comment by Saallen** [comment]
Hey @edrushka @mmmavis 
Since we are just under 4 weeks from closing the call and the tate need to action this today I am going to make a one page form this this newsletter- the form will mirror our own submission process.
If we need to change this later in the week we can

**Comment by edrushka** [comment]
This looks good - love the zine background! 🎨 

For the section 'Is there another space you believe this exhibit could be shown within?' it needs a link to the Spaces page so people can read more about the additional spaces. 

Also for that section, if you chose some spaces it will submit the form and not take you to the next section - was that intentional?

**Comment by Saallen** [comment]
Hey
Good catch- does the choosing of the space not lead to t&cs?

**Comment by Saallen** [comment]
I am finding it hard to link out to the website- its looks pretty fugly..

**Comment by edrushka** [comment]
I know - I couldn't figure it out either. Maybe create a shortlink for the Spaces page and edit that question to read:  'Is there another space you believe this exhibit could be shown within? Read more about the other spaces here: shortlink'

**Comment by mmmavis** [comment]
Hi @Saallen and @edrushka ! I was on PTO Tuesday and Wednesday. Anything I can help here? 😄
