### ISSUE TITLE
Mozfest.org leading ppl astray

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#69]
Hey @edrushka 
I keep getting pinged from folks about the fact that mozfest.org is leading ppl to mozfest 2015 website.

apart from telling these folks to clear their cashe is there another solution to helpo allivate this confusion?

😕

**Comment by edrushka** [comment]
cc @cadecairos 

It works fine for me, and I had Mavis check it out as well. Anything we can do for people?

**Comment by marcwalsh-zz** [comment]
Just seen this as an open issue. I tried it for myself and I'm being directed 2015.mozillafestival.org and I've cleared my cache etc.

**Comment by cadecairos** [comment]
I just double checked the settings for mozfest.org and www.mozfest.org in AWS, and it's all configured to redirect to the right place.

I don't think people are hitting a browser cache issue. It's more likely a DNS cache in their operating system or a stale DNS cache from their ISP.

That said, this configuration has been in place for weeks now...

**Comment by edrushka** [comment]
@cadecairos is there anything we can do? This is really problematic as the information and links are completely different for this year's festival. We have our call for proposals open now, and if people are hitting the 2015 page and try to submit a session, they will get an error message.

**Comment by cadecairos** [comment]
There's nothing more we can do on our end beyond completely replacing the 2015 site with a redirect.

**Comment by edrushka** [comment]
Is that simple to do? I have no idea about the amount of work that entails.

**Comment by cadecairos** [comment]
It's pretty simple, 30 minutes work to get in place

**Comment by edrushka** [comment]
I think we should go ahead and do this. It's highly problematic for people to be seeing the wrong year. Is this something Mavis can do or does it fall to you, Chris?

**Comment by cadecairos** [comment]
I'll have to take care of it, the work all happens in Amazon Web Services

**Comment by edrushka** [comment]
Thanks Chris! 🌵  <-- cactus of gratitude. Let me know if you want me to file a ticket in your devops repo.

**Comment by cadecairos** [comment]
haha! Yes, please file a ticket here https://github.com/mozillafoundation/mofo-devops/issues/new

**Comment by edrushka** [comment]
Chris fixed this with a redirect in https://github.com/MozillaFoundation/mofo-devops/issues/376

THANKS!
