### ISSUE TITLE
Scope What to Expect page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#7]
Link to current page: https://2015.mozillafestival.org/expect

**What needs updating by June:** 
- [ ] Mark speech
- [ ] Weekend outline- new dates
- [ ] Update content to 2016
- [ ] Freshen page

**Other thoughts/ideas**:
- [ ]

**Comment by edrushka** [comment]
Need to tweak the copy as per https://github.com/MozillaFoundation/Mozfest2016_production/issues/5
- explain the format- what you will see when you walk in the door. Explain talks and interactive sessions.
- explain that you can submit sessions to be part of the schedule
- explain spaces and why are they important

**Comment by edrushka** [comment]
@KevZawacki how are we doing on getting Mark's signoff for the speech bubble? We're going to need final copy on that no later than EOD May 24.

**Comment by KevZawacki** [comment]
@edrushka Still awaiting feedback -- I'll nudge Mark and let him know we're on deadline.

**Comment by edrushka** [comment]
@Saallen and @KevZawacki I've drafted new text for Participating At MozFest and also proposed a new section called What Is MozFest Like? to address Sarah's comments above. Please review here: https://public.etherpad-mozilla.org/p/whattoexpect-copy-2016

**Comment by KevZawacki** [comment]
@edrushka Excellent! Just added my revisions -- only a couple prepositions and semicolons.

**Comment by Saallen** [comment]
Hi- I made a few small changes to the first what is MozFest-
I just tweeked some lines so that what we are saying in this document is what we will deliver over the weekend.
Loved the particpating at MozFest paragraph- really great work @edrushka

**Comment by edrushka** [comment]
Note we should add video in here, since it's not super obvious on the landing page

**Comment by edrushka** [comment]
Thanks @Saallen - I took another pass to integrate your ideas while keeping the wordcount as low as possible. Please take a final review: https://public.etherpad-mozilla.org/p/whattoexpect-copy-2016

@vazquez do you think we should embed the video directly rather than linking via text? (see how I've done it in the etherpad above)

**Comment by vazquez** [comment]
I think embedding the video would be a nice touch. I really don't foresee any technical complications.

**Comment by edrushka** [comment]
I guess my only concern is with the amount of copy, plus potentially the video, this page might get super long.

**Comment by edrushka** [comment]
@vazquez let's go ahead and implement the new copy and the embedded video

**What is MozFest like?** 

MozFest is a diverse, highly interactive event with something for everyone. The festival kicks off Friday evening with a science fair, where attendees can stroll around and check out presentations on inspiring ideas and projects, many of which were developed at previous MozFests. Saturday and Sunday are filled with participant-led sessions that generally run between one and three hours. These might be interactive labs where participants can learn something new or share their knowledge; small group breakout discussions where bright minds debate the most pressing issues facing the Internet today; or design sprints dedicated to hands-on making, hacking and producing a ‘thing’. 

Sessions are organized into spaces -- physical and thematic learning hubs based around a broad topic, like science, art, or journalism. Ongoing, interactive experiences weave between spaces, connecting thematic threads and allowing participants to explore topics in a self-directed way.

Some people choose to enjoy MozFest by completely immersing themselves in a single space, while others like to roam around the venue. Both options are equally welcome, and the festival features pathways -- curated sets of related sessions that explore a subject area like open data, dealing with online harassment, or mobilizing communities -- to guide you between spaces.

The festival wraps on Sunday evening with a demo party, where we showcase and celebrate what we built together. 

*\* Embed Video Here **

**Participating at MozFest**

MozFest is an annual festival where hundreds of passionate people gather to wield the Web for good. We create, teach and learn as a community in order to make the Internet, and by extension the world, a better place. Guiding the festival is Mozilla’s core learning vision: learning should be hands-on, immersive, and done collectively. 

MozFest is populated with people that are open, friendly and eager to help. Participants of all ages and skill levels are welcome. We believe that everyone has something to contribute. Youth especially are encouraged to come and lead sessions -- we’re dedicated to mentoring and celebrating tomorrow’s leaders. For our youngest participants, on-site day care and activities are provided.

We try to accommodate all interaction styles at MozFest. While many sessions are hands-on and fully interactive, we also have plenty of listening-based activities for those who participate best in that manner, as well as individual maker stations where attendees can focus -- individually or in a group -- on a single activity.

MozFest is proud to host attendees from all over the world. Because each of us arrives with different backgrounds, experiences and expectations, MozFest has [Participation Guidelines](https://2015.mozillafestival.org/guidelines) outlining how we interact. Theses are ground rules guiding how participants, facilitators, space wranglers, staff, volunteers and vendors engage with one another during the festival, so we can all enjoy a safe, respectful and rewarding weekend.

**Comment by vazquez** [comment]
@edrushka –
- Are we keeping Mark's speech? 
- Are we keeping "Participating at Mozfest"?
- Are we keeping "Weekend Outline"?

**Comment by edrushka** [comment]
Oops. I realize I shouldn't have put the Ready for Ricardo label on quite yet!
- yes we're keeping/updating Mark's speech. Waiting for his final signoff now.
- yes we're keeping "Participating at Mozfest". Updated copy is in the comment above.
- @Saallen do you want to hide "Weekend Outline" until we have a better idea of what the mainstage will look like?

**Comment by vazquez** [comment]
This is a screenshot of how the page would look like. There does seem to be quite a bit of text. Perhaps cutting down "What is MozFest like" could help, since we have the video.

![screen shot 2016-05-20 at 15 19 39](https://cloud.githubusercontent.com/assets/1119821/15439342/7ed54170-1e9e-11e6-8743-661b04a68745.png)

**Comment by edrushka** [comment]
yah, that is certainly a wall of text. I propose we eliminate the first paragraph of the "Participating at MozFest" section. I can work those ideas into the "About" page.

**Comment by edrushka** [comment]
@Saallen @KevZawacki what are your thoughts on moving Mark's speech bubble to the 'About' page? Currently it lives on "what to expect", but as you can see on Ricardo's mockup above, that page is getting far too text-heavy.

**Comment by KevZawacki** [comment]
@edrushka I like that idea -- "What to expect" does seem a bit crowded at the moment.

**Comment by Saallen** [comment]
@edrushka I think that makes sense. Really like having the video on this page now too 🌷

**Comment by vazquez** [comment]
The what to expect page looks better without Mark's speech:
![screen shot 2016-05-24 at 10 01 50](https://cloud.githubusercontent.com/assets/1119821/15506745/c19e1360-2196-11e6-8780-e273744f1edd.png)

and the About page now has Mark's speech:

![screen shot 2016-05-24 at 10 02 16](https://cloud.githubusercontent.com/assets/1119821/15506747/c60ee01e-2196-11e6-9386-be3896cea8e0.png)

**Comment by edrushka** [comment]
Wooo! Yah! That looks great @vazquez

**Comment by edrushka** [comment]
@Saallen still waiting on your thoughts about the Weekend Outline. Do you want to simply update the dates and leave as-is, or should we remove the section altogether until the fall? I'm inclined to leave it (even though we might not do evening lightening talks) to give people a sense of the weekend, and how much time they should take off work on Friday (since we got feedback about people thinking Friday was a full day).

**Comment by Saallen** [comment]
@erika yes it does provide a good sense of when to arrive- it does look kinda lost now though at the bottom- would it be more helpful to go under the "what MozFest is like" as you read about the festival and what happends, then next is timings for further clarification? We can leave lightening talks for the time being and edit later in the year when we know whats actually happening

**Comment by edrushka** [comment]
+1 makes sense to move up
New dates are
Friday Oct 28
Sat Oct 29
Sun Oct 30
