### ISSUE TITLE
Undefined Space when choosing Two Cities under MozEx.

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/2016.Mozillafestival.org#71]
Hello!

Whenever I've been uploading proposals using the call for proposals form and it's a piece that is going into the Moz Exhibition and I've selected 'A Tale of Two Cities' as the space on the second page, it appears on GitHub as an undefined space.

**Comment by mmmavis** [comment]
Hi @marcwalsh , thanks for reporting it! This should be fixed now! 💃
