### ISSUE TITLE
Translations for non-English submissions

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/2016.Mozillafestival.org#72]
Hey everyone, 

Just a quick question that was brought up on the programme repo. 

Is it worth adding a translated version of non-english submissions as a comment. Bit of an out-there question but is there a way to do this automatically, or would it need to be whenever I add a submission that I need to just translate it myself using Google or something similar?

**Comment by edrushka** [comment]
Yes. Ali and I discussed and we built this into the L10N plan. Basically everything will be done through comments on Github. We just need to tag the localizer so they see it if we've written a question.

**Comment by marcwalsh-zz** [comment]
Awesome! Makes sense, thank you! 👍
