### ISSUE TITLE
Fringe events not loading

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#73]
Helllo @mmmavis 
I just uploaded a fringe event via the website 4 hours again and then approved on the spreadsheet 
https://docs.google.com/spreadsheets/d/10IecT0M6d28MREgGGHscyy87RliCbTQQVy8IeRILUBc/edit#gid=1651772276

However it is not appearing  on the website...I am not sure if I broke the voodoo magic...Can you have a look when you get some time? I prepped a tweet to celebrate this awesome page going out later tomorrow so it would be awesome to have it working 🍊

**Comment by mmmavis** [comment]
Hey @Saallen , if anything it shouldn't be you who broke the voodoo magic... it would be the voodoo magic itself being not powerful enough 😉 

This is what I'm seeing on the MozFest site
<img width="459" alt="screen shot 2016-07-26 at 2 48 21 pm" src="https://cloud.githubusercontent.com/assets/2896608/17156704/08dc2cb4-5340-11e6-88cf-7f713a3138ef.png">

... which match the 3 approved events on the spreadsheet. Is there any other event that should've appeared on the fringe page but didn't make its way there?

**Comment by Saallen** [comment]
Hi @mmmavis this is great- I obviously was not patient enough 🕐 
Thanks  🍊
