### ISSUE TITLE
Change CTA on MozFest homepage

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#75]
The current CTA on the MozFest site reads:

_Submit a Session for MozFest 2016_

_We invite people from all fields: policy, science, journalism, technology, arts and more. MozFest is for everyone, regardless of your gender, geography, age or language._

_Submit a Session_

**Please change to:**

Buy a Ticket for MozFest 2016

Join leaders of the open Web -- artists, activists, educators, scientists, journalists, policy-makers and technologists -- who are building a better internet.

Buy a Ticket (button text)
## 

Call for proposals ends EOD August 1, so if this could go live on the 2nd, that would be ideal.
cc @mmmavis @Saallen

**Comment by alanmoo** [comment]
Deployed to production, will propagate as CDN updates.
