### ISSUE TITLE
GitHub displaying Arabic in LTR not RTL

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/2016.Mozillafestival.org#77]
Heya 

Just had a comment through from one of the facilitators, and I've had a double check as well. It seems as through when the sessions appear on GitHub in Arabic, the Arabic parts appear as LTR.

Not sure if this is because it's mixed with English text so everything is just shown in LTR or even if there's anything we can do to change it without messing up @mmmavis creation!

Cheers :),

**Comment by Saallen** [comment]
This is something we thought about for the form but never for the github repo- thanks @marcwalsh

**Comment by edrushka** [comment]
Closing this, and noting that this issue is also being discussed for the schedule app (see https://github.com/mozilla/schedule-app-core/issues/260 )
