### ISSUE TITLE
Add linked text on Tickets page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#79]
We've been hearing that it's not clear the ticket buttons are what you need to press to buy tickets on https://mozillafestival.org/tickets

At the end of both the youth and adult ticket description paragraphs, please add a line that says "Buy a youth ticket."/"Buy an adult ticket." that links to the youth/adult ticket page.

cc @marcwalsh

**Comment by alanmoo** [comment]
Clicking those "tickets" at the top doesn't bring you to a new page. Should clicking these new "links" make the same popover appear? Or is there a proper tito link I can use? 

(@mmmavis, can you shed some light on how the popover is happening? Is that tito script doing some sort of magic? I'm concerned that adding an extra link to that paragraph isn't going to be as easy as it should be.)

**Comment by alanmoo** [comment]
(Note that it would be extremely trivial to update the text on the existing links, so they have a clear CTA- "Buy Adult" or "Buy Adult Ticket")

**Comment by mmmavis** [comment]
@alanmoo yay tito script is def doing magic. I'm thinking maybe we can mock what we are doing for creating the red ticket buttons: https://github.com/mozilla/mozillafestival.org/blob/3e1aa668bd2b4ea1a9c35c336c52d507b50b6737/pages/tickets.jsx#L9-L18 We can just tweak the stylings so that "Buy a youth ticket."/"Buy an adult ticket." appear like regular text links (not button looking).

**Comment by alanmoo** [comment]
Thanks for that guidance, @mmmavis. I'll take a look at it now and see what I can do.

**Comment by alanmoo** [comment]
A UX thought: if someone is buying a child's ticket, aren't they probably also in need of an adult ticket? Seems odd to force two different transactions. Would it be better to link to https://ti.to/Mozilla/mozfest-2016/ and let them choose?

(After playing around with it more, adding those links at the end of the paragraph really doesn't feel like the right solution, especially considering the amount of hackery involved. Plus it's not very accessible.)

**Comment by alanmoo** [comment]
@edrushka thoughts?

**Comment by edrushka** [comment]
Confirming that I understand correctly:  both the youth and adult ticket description paragraphs would have a linked sentence that reads "Buy a youth ticket."/"Buy an adult ticket." that would link to https://ti.to/Mozilla/mozfest-2016/

This works for me.
