### ISSUE TITLE
Write new copy for landing page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#80]
There are two banners that need updating:

1) Info banner 
The world’s leading event for and by the open Internet movement.
Join us to build, debate, and explore the future of our lives online.

2) CTA banner
Buy a Ticket for MozFest 2016
Join leaders of the open Web -- artists, activists, educators, scientists, journalists, policy-makers and technologists -- who are building a better internet.

**Comment by edrushka** [comment]
Time booked on Sept 6 with Paul and Kevin to update this copy.

**Comment by kristinashu** [comment]
Done! Copy can be seen here https://redpen.io/tce99aae1e32140127
