### ISSUE TITLE
Design updates to landing page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#81]
Replace seated crowd shot currently on https://mozillafestival.org/ with something more active and representative of the network. It doesn't necessarily have to be a photo.

Colour should reference the neon palette from the [2016 Style Guide](https://github.com/MozillaFoundation/Mozfest2016_production/issues/76).

**Comment by edrushka** [comment]
Here is the copy: https://public.etherpad-mozilla.org/p/mozfestcopy

**Comment by edrushka** [comment]
Please mock up landing page with
- new copy and image for main banner (copy in pad above)
- new copy for CTA section (copy in pad above)

We'll get signoff on your design before we send to Alan for implementation.

**Comment by kristinashu** [comment]
This will include:
- new banner background image (few options)
- make video button more obviously a button
- update banner copy
- update CTA section copy
- remove 'buy ticket' button

**Comment by kristinashu** [comment]
@edrushka @sabrinang here's what I'm thinking for the home page https://redpen.io/tce99aae1e32140127

It has the updated copy, branding and changes mentioned above. Because there is more text than before, a photograph background looks too busy so I'm using the our background pattern. Let me know what you think!

**Comment by kristinashu** [comment]
@edrushka I've updated the home page copy based on the redpen comments https://redpen.io/gx8ec85042b38ea596

I'm sure there will still be some more changes so just let me know what you decide.

**Comment by edrushka** [comment]
Awesome! Thank you so much. Would you be able to do one additional variant where you add the words "and by" back into the first line of text. So it should read:
The world's leading event for -- and by -- the open internet movement. 
You can try italics if the em-dashes look dumb.

**Comment by kristinashu** [comment]
Em dash was weird because it's close to the line break so italics kinda works https://redpen.io/sy66b4fde211454a2d

**Comment by edrushka** [comment]
haha! Those italics are so perky! That doesn't work as well in real life as it did in my imagination.

@Saallen @KevZawacki can you please sign off on the redpen without the italics: https://redpen.io/gx8ec85042b38ea596 I changed the CTA text at the bottom so please review. Not sure I nailed it.

**Comment by KevZawacki** [comment]
@edrushka Looks good, non-italics and new CTA both

**Comment by kristinashu** [comment]
Great, all done! Here is the lastest version https://redpen.io/tce99aae1e32140127

Implementation ticket is here https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/97

![website-03_home](https://cloud.githubusercontent.com/assets/1068783/18560596/2ec07cc8-7b31-11e6-9974-e475b4a7daae.jpg)

**Comment by Saallen** [comment]
Soooo prettyyyyy 🌷
