### ISSUE TITLE
Add Marc's photo and bio to Team page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#83]
Marc, can you please submit your photo and bio for the [Festival Team page](https://mozillafestival.org/team). Please keep to the shorter wordcount. Thanks!

**Comment by marcwalsh-zz** [comment]
See below!

Marc Walsh is the Production Coordinator for MozFest 2016.  His work focuses around large scale events and television production having previously worked on Glastonbury Festival, The FA Cup and the National Television Awards. This is Marc's third year working with Mozilla on the festival after having been a Ravensbourne volunteer for two years before that.  

![Photo is here!](https://cloud.githubusercontent.com/assets/14007066/18083807/b8657bbe-6e9c-11e6-80a8-8e8841884b9a.jpg)

@edrushka @Saallen - Would either of you be able to spell / grammar check this for please! :)

**Comment by edrushka** [comment]
How's this @marcwalsh?

Marc Walsh is the Production Coordinator for MozFest 2016.  His brings valuable experience in large-scale event and television production, having previously worked on Glastonbury Festival, the FA Cup and the National Television Awards. A volunteer for his first two years, this is Marc's fifth MozFest.

**Comment by hannahkane** [comment]
Adding @alanmoo as an assignee to get this up on the site as soon as is reasonable.

**Comment by marcwalsh-zz** [comment]
Looks good just made one correction but the below is good to go! :) Thanks @edrushka 

Marc Walsh is the Production Coordinator for MozFest 2016. He brings valuable experience in large-scale event and television production, having previously worked on Glastonbury Festival, the FA Cup and the National Television Awards. A volunteer for his first two years, this is Marc's fifth MozFest.
