### ISSUE TITLE
Add link(s) to Github

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#85]
When curation is complete and people who proposed have been notified (week of Sept 12-16), we need to add link(s) to the [Sessions and Spaces](https://mozillafestival.org/spaces-and-sessions) page.

@Saallen how did we do this last year? 

One way we could approach it is to 
a) add a link at the end of the Spaces and Sessions paragraph at the top that reads:
See All Sessions here (with a link to all the accepted sessions in Github), and
b) modify each space description with a line that reads: See the sessions in this space (with a link to the sessions labelled with that space in Github)

**Comment by Saallen** [comment]
in 2015 we linked to the github page.
In 2016 I think we do the same but add a note when the schedule will be ready.
Pushing people to a github page to see what sessions they can attend is not a great way to share and I dont think a fair way to raise the profile of a session. Lets just do one link but chat about when we think we can have the schedule up

**Comment by edrushka** [comment]
The schedule will likely be live a week or so before the event, and we will link to it from the top nav. This solution doesn't replace linking to the final schedule, but instead provides some details on sessions before the schedule is ready.

I'm going to argue for keeping both a) and b) in my suggestion above 😄  I think a 'see all sessions' supported by 'see session in this space' actually offers decent value to people before the final schedule is ready. I like your idea of indicating when the schedule will be ready. We could change a) to read "The schedule for MozFest will be published in mid-October. Until then, see all sessions here."

**Comment by Saallen** [comment]
I like it 👍

**Comment by edrushka** [comment]
@alanmoo Here's a summary of the discussion above:

1) add a link at the end of the Spaces and Sessions paragraph at the top that reads:
The schedule for MozFest will be published in mid-October. Until then, [see all sessions here](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22). 

2) Add a line to the end of each space description that reads "See the sessions in this space." and links to individual sessions in that space (links below):
- [Digital Arts and Culture](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+Digital+arts+and+culture%22)
- [Journalism](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+Journalism%22)
- [Open Science](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+Open+science%22)
- [Open Badges](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+Open+badges%22)
- [Fuel The Movement](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+Fuel+the+movement%22)
- [Localisation](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+Localisation%22)
- [Youth Zone](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+Youth+zone%22)
- [Demystify the Web](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+Demystify+the+web%22)
- [A Tale of Two Cities: Dilemmas in Connected Spaces](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BSpace%5D+A+tale+of+two+cities%3A+dilemmas+in+connected+spaces%22)
- [MozEx (Art Exhibit)](https://github.com/MozillaFoundation/mozfest-program-2016/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Session+accepted%22+label%3A%22%5BExperience%5D+Moz+Ex%22)
