### ISSUE TITLE
Update Spaces & Sessions page with bios

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#86]
We are collecting the space wrangler bios (text and photo) in https://github.com/MozillaFoundation/Mozfest2016_production/issues/56

During the second week of the Sept 16 heartbeat, we can add whatever bios have been submitted to the right hand column of the [Spaces and Sessions](https://mozillafestival.org/spaces-and-sessions) page. 

I can't see what we did last year because the 2015 site has a redirect. @Saallen do you remember? Did we have bios and photos? If so, we should be able to reuse the code.

**Comment by Saallen** [comment]
In 2015 we had names and twitter handles
in 2014 we had bios and redirects - which i think is a better format for celebrating these folks

We have never had photos before so this is 🏆

**Comment by edrushka** [comment]
@Saallen Where did the redirects go in 2014?  Do you want this again this year i.e. their name links to their blog/twitter and bio and photo are underneath?

@alanmoo do you need design help if we've never used photos before?

**Comment by alanmoo** [comment]
Yeah, that space is a bit narrow as is, so some design guidance would be useful.

**Comment by edrushka** [comment]
cc @hannahkane an additional bit of design work needed here. Please assign to Sabrina, if appropriate, for next heartbeat.

**Comment by edrushka** [comment]
Here are the bios (second tab): https://docs.google.com/spreadsheets/d/100wmCld-YGysLHCpzYgovwctJkezPqQgFcOJ65mjyUk/edit#gid=1306798567

Photos are linked from here, but are also available in this drive folder: https://drive.google.com/open?id=0B4rEOP1A0tc0YkVSeUpfVjZ0a0E

**Comment by alanmoo** [comment]
@kristinashu I'm unassigning myself for now, toss it to me when design is ready?

**Comment by kristinashu** [comment]
I'm thinking we can reuse the light box from the [ticket page](https://mozillafestival.org/tickets) 
<img width="941" alt="screen shot 2016-09-07 at 4 18 22 pm" src="https://cloud.githubusercontent.com/assets/1068783/18331850/c23ccdf6-7516-11e6-9aca-92e473f14a26.png">

We would update wrangler names on the Spaces & Sessions page to be links. If a user clicks on a wrangler's name then a light box opens up with the persons photo and bio. 
<img width="1071" alt="screen shot 2016-09-07 at 4 18 07 pm" src="https://cloud.githubusercontent.com/assets/1068783/18331854/c621c566-7516-11e6-8728-2e13e2ea6852.png">

This layout is flexible and will fit different bio lengths, with a photo or without a photo. If we don't have a photo or a bio then the wranglers name won't be link color and won't open a light box.

**Comment by alanmoo** [comment]
I think Tito is creating that light box, so it's not something we easily have access to. Correct me if I'm wrong, @mmmavis?

**Comment by mmmavis** [comment]
@alanmoo yes i think lightbox is part of the Tito magic

**Comment by kristinashu** [comment]
@alanmoo I still think light box approach will be the most straight forward way to do this. Is there a default/example I should model the design after?

**Comment by Saallen** [comment]
Hey- I am ti.to will share their magic- I can put you in contact with them if you like?

**Comment by alanmoo** [comment]
Thanks @Saallen, but I don't think that will help much. @gvn maybe you can help, do we have a standard modal?

**Comment by gvn** [comment]
We don't have a standard modal. Honestly, modals are not great (especially in regards to mobile/responsive layouts) and should be avoided if possible, but if we must use them then we should probably add one to `mofo-ui`.

**Comment by kristinashu** [comment]
Thanks everyone for the input. We've decided to create a new page to house all the bios.

https://redpen.io/nw70a0d8f24c9bc983
![website-wranglers 2x](https://cloud.githubusercontent.com/assets/1068783/18488191/3b6516c6-79ad-11e6-8fd9-1eefcb0deefb.jpg)

Wrangler's names on the [Space & Sessions page](https://mozillafestival.org/spaces-and-sessions) will link to the [Wrangler page](https://redpen.io/nw70a0d8f24c9bc983) and scroll down to that person's bio and pic.

We will only include Wranglers who and shared their bio and a pic. Currently we only have 14.

Should wranglers be in alphabetical order? By first name or last name?

**Comment by edrushka** [comment]
Yaaas! The Friends and Allies dream is alive!! @kristinashu [here is the ticket](https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/35) so you can understand the additional content we might eventually add to this page as you design it.

**Comment by kristinashu** [comment]
Cool, my only concern would be page length. There are 16 mocked up right now and we probably wouldn't want too many more. Mobile would start to get a little cray cray.

**Comment by kristinashu** [comment]
@edrushka @hannahkane I just spoke with @alanmoo and here is what we are thinking:

Sounds like we need a home for:
- Space wranglers ([mocked up as a link from Spaces & Sessions page](https://redpen.io/nw70a0d8f24c9bc983))
- Sponsors (doesn't currently exist but we will need it)

We think this could be one page with tabs (using tab component and fellowship bio layout from https://science.mozilla.org/programs/fellowships/fellows). 

We could group in the Team page here as well ([already exists as a link in the footer](https://mozillafestival.org/team)). Each tab would have the same layout (circle image with name and bio). So the one page would include three tabs:
- Team
- Space Wranglers
- Sponsors

We link to this tabbed page from:
- the footer (replacing the Team page link)
- Space & Sessions page (to individual's name and bio)

Would that work for you @edrushka? What would we call it?

@hannahkane we are aware there is some scope creep happening here but this will make the site more flexible for the addition of Sponsors and any others that might come up.

**Comment by hannahkane** [comment]
@alanmoo - can you estimate the extra dev time this solution would require?

**Comment by alanmoo** [comment]
It's probably a solid day of work, maybe a little over. But I still think it'll be less work than popovers in the long run.

**Comment by hannahkane** [comment]
Just flagging that this, the /Foundation page, and Gigabit page are all entering the build phase at the same time. Will think about how to spread that work out so it doesn't all fall on Alan.

@alanmoo - could you work on this page this week? definitely more important than the web lit map thing.

**Comment by alanmoo** [comment]
Yes; is this the priority of those 3 @hannahkane?

**Comment by hannahkane** [comment]
I think this is the most ready-to-go. In terms of priority, both this and /Foundation have upcoming deadlines.

**Comment by edrushka** [comment]
What I really like about this is that is flattens the hierarchy of the festival team. It's essentially still a Team page, we're just broadening the definition of the team. We could keep the name "Team", and specify that everyone currently on the team page is in the "production team". Or, we could call the page Co-designers, or Collaborators or something similar.

**Comment by edrushka** [comment]
@alanmoo @hannahkane I can have the content for 3 sections ready asap:

1) Space Wranglers (photos and bios -- 32 entries -- content [here](https://docs.google.com/spreadsheets/d/100wmCld-YGysLHCpzYgovwctJkezPqQgFcOJ65mjyUk/edit#gid=1306798567), mockup [here](https://redpen.io/nw70a0d8f24c9bc983)).
2) Partner Organizations (logos/wordmarks) -- around 6-10 entries -- will collect these ASAP.
3) Production Team (photos and bios already done [here](https://mozillafestival.org/team), modify to use same styling as Space Wranglers above)

If we secure corporate sponsorship, we'll need an additional section
4) Sponsors -- likely around 1-5 entries (logos/wordmarks)

Does that work?

**Comment by hannahkane** [comment]
cc @mmmavis who will do the implementation. (Sorry, @edrushka, I just realized we're having a conversation about this in a chat channel you're not in.) Going to move @mmmavis to MozFest work, since she's been doing a bunch of MozFest related stuff. This frees up @alanmoo to work on the /Foundation page, which is also high priority.

**Comment by kristinashu** [comment]
I've just updated redpen with how the tabs could look https://redpen.io/so550ced71853c074b

I'm recommending shorter titles for the tab so the tabs will work better on narrower screen widths.

**Comment by edrushka** [comment]
Oh nice! Shorter titles work for me given the design constraints. @Saallen please sign off on this redpen before we initiate the build.

**Comment by kristinashu** [comment]
Opened an implementation ticket https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/96 and a prep images ticket #95

**Comment by Saallen** [comment]
Hey @kristinashu @edrushka This looks great
My only flag would be what if we didnt get any sponsors? Would this make the look of the tabs seem lacking?

**Comment by kristinashu** [comment]
Thanks @Saallen! It would not be a problem to have 3 tabs (even 2 tabs would be fine https://science.mozilla.org/programs/studygroups/join).

**Comment by Saallen** [comment]
Great to know thanks
