### ISSUE TITLE
Add Kevin's photo and bio to the Team page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#87]
@KevZawacki, we would love to include you on the MozFest team page 😄 

Can you please submit a photo and short bio? See other examples [here](https://mozillafestival.org/team) - please keep to the shorter wordcount. Thanks!

@Saallen can you please confirm what Kev's title should be? cc @HPaulJohnson

**Comment by KevZawacki** [comment]
Oh, my... I'm flattered!

Perhaps:

Kevin Zawacki
Communications Manager

Kevin Zawacki is Communications Manager for the Mozilla Foundation, and has a background in journalism and public relations. As a member of the MozFest team, Kevin works on copy writing, media relations, and main stage production. 2016 will be Kevin's third MozFest.

![13900073_10100990018991080_9154886712106571191_n](https://cloud.githubusercontent.com/assets/11045250/18150269/91fa842a-6fb3-11e6-9b4f-72801ea6760a.jpg)

**Comment by Saallen** [comment]
@KevZawacki While I love the handsome photo your bio says nothing about D&D
I think you need a strong sentence that celebrates your awesome work on coordinating that space....suggestion below

Kevin Zawacki is Communications Manager for the Mozilla Foundation, and has a background in journalism and public relations.  Kevin brings his magic to copy writing, media relations and this year is the mastermind behind the new Dialogues and Debates speakers series. 2016 will be Kevin's third MozFest.

**Comment by KevZawacki** [comment]
@Saallen Perfect 👍

**Comment by Saallen** [comment]
Media mogul?
Comms Mogul?
Comms wrangler?
Comms Manager- but this doesn't encompass the D&D space...
Anyone got suggestions?

**Comment by KevZawacki** [comment]
@Saallen Comms Manager & Speaker Series Designer?

**Comment by Saallen** [comment]
Sure-

Sarah Allen

Events Manager and Mozilla Festival Producer
Mozilla Foundation

Find out more about MozFest https://mozillafestival.org/ and follow the
conversation on twitter https://twitter.com/mozillafestival?lang=en-gb

**Comment by alanmoo** [comment]
Sorry, I'm missing some context- what are you suggesting gets changed, @Saallen and @KevZawacki? (The original ticket is now live)

**Comment by edrushka** [comment]
The job title under Kevin's name should read Comms Manager & Speaker Series Designer
