### ISSUE TITLE
"tickets sold out" updates

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/2016.Mozillafestival.org#88]
Blocked by #81.

Create a PR so that when tickets do sell out, this is easy to merge.

**Comment by alanmoo** [comment]
Hmm, #81 is for something else. @edrushka @kristinashu what's the ticket for design of the "tickets sold out" update?

**Comment by kristinashu** [comment]
I've updated https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/81 to be more reflective of what the changes will be. From what I gather, once tickets are sold out we just don't link to it anymore.

**Comment by kristinashu** [comment]
@edrushka can you confirm that once tickets are sold out all we do is remove the "ticket" link in the nav bar? And the new home page design removes the link on the home page https://redpen.io/tce99aae1e32140127

When does it usually sell out? Couple days before MozFest or pretty soon?

**Comment by edrushka** [comment]
When tickets sell out:
- remove the ticket link in the nav
- ensure that the new landing page with the updated CTA #81 is implemented ASAP

@Saallen when should we expect it to sell out? Can we implement #81 (which changes the CTA to Sign Up for remote participation info, but keeps the tickets link at the top) before it actually sells out?

**Comment by Saallen** [comment]
😭 I really hope so
Yes!

**Comment by kristinashu** [comment]
Excellent! So implementing the home page updates can happen anytime soon https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/97

@mmmavis has just pointed out that people could still visit https://mozillafestival.org/tickets URL even if we stop linking to it in the nav (if they type in the url or had an old link to it). So we should probably update the copy on it to say "tickets are sold out".

When tickets sell out, this ticket will be to:
- [ ] remove the "tickets" link in the main nav
- [ ] update the copy on https://mozillafestival.org/tickets to say "tickets are sold out"

**Comment by alanmoo** [comment]
Since we're so close, I'm closing this as per @edrushka. If we do sell out, we'll just remove the link from the top nav.
