### ISSUE TITLE
Merge medium.com/mozfest-2016 & medium.com/mozilla-festival

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/2016.Mozillafestival.org#89]
We currently have two different MozFest publications on Medium:

http://medium.com/mozfest-2016
and
https://medium.com/mozilla-festival (2015 publication)

MoCo branding has requested we merge into one single publication, with different sections for each year. I think that's a good idea, too.

It should be easy to port content from http://medium.com/mozfest-2016 to https://medium.com/mozilla-festival. Once complete, I can open a ticket to change the mozfest.org blog footer link. I also apply the Medium brand guidelines (red header, white text, etc.)

cc @edrushka @Saallen @HPaulJohnson Any objections or flags?

**Comment by edrushka** [comment]
Makes sense to me.

**Comment by Saallen** [comment]
GOFORIT

**Comment by KevZawacki** [comment]
Old Medium blog deleted; in the process of porting content over to Medium.com/Mozilla-Festival
