### ISSUE TITLE
Secure 2-3 additional D+D speakers

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/2016.Mozillafestival.org#90]
To ensure we have three robust D+D blocks at MozFest, we'll want to secure 2-3 more speakers.

Below, a list of potential candidates. @edrushka, @HPaulJohnson, @Saallen: If you have a moment, please take a quick look and offer feedback / **additional speakers**. I'll begin outreach next week. 
- Dr. Safiya Noble //  academic and activist // [clip](https://safiyaunoble.com/) // Vanessa has invited
- Catherine Bracy // director at Code for America // [clip](https://www.ted.com/talks/catherine_bracy_why_good_hackers_make_good_citizens) // Likely speaking!
- Josef Davies-Coates // founder of The Open Co-Op // [clip](https://www.youtube.com/watch?v=2KPW7Xklye4) // Kevin to invite
- Andre Brock // professor // [clip](https://www.youtube.com/watch?v=BQMfBslxI18) // Vanessa to invite
- Morgan Marquis-Boire // journalist and security expert // [clip](https://www.youtube.com/watch?v=bOK_KAXbTe8) // Kevin to invite
- Ben Hammersley // journalist and futurist // [clip](https://www.youtube.com/watch?v=F_1GIlzRS0M) // Kevin to invite
- Sahar Aziz // professor // [clip](https://www.youtube.com/watch?v=qj9OAZU1jvU) // Interested! Kevin is speaking w/ next week
- Simone Browne // professor // [clip](https://www.youtube.com/watch?v=IsMFdiLsqbg) // Kevin invited
- Jensine Larsen // tk

**Comment by edrushka** [comment]
👍 let me know if I can help. Great that Vanessa is assisting with the invites. Are any of these speakers London-based, or able to speak on topics specific/appealing to a London audience?

**Comment by Saallen** [comment]
Hey @KevZawacki 
Thanks for this great list and tough to choose just one.
Great list of speakers and quiet diverse.
Personally I am loving Safiya.
I think Sahar would be very strong especially with all our arabic localisation thread.
I would also be interested to hear more about Josef.

**Comment by KevZawacki** [comment]
Update:

 -- Catherine Bracy is likely speaking
-- Sahar Aziz is interested; I have a phone call with her next week
-- Invite sent to Simone Brown today

@HPaulJohnson @Saallen @edrushka

**Comment by KevZawacki** [comment]
Simone Browne has accepted :-)

Closing this ticket.
