### ISSUE TITLE
Update Medium footer link on MozFest.org

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/2016.Mozillafestival.org#91]
The "Read The Blog" footer links to a now-defunct Medium page. Can we update the link to www.medium.com/mozilla-festival?

![screen shot 2016-09-13 at 10 25 30 am](https://cloud.githubusercontent.com/assets/11045250/18477665/6b71d89c-799c-11e6-8162-ffa1a33e5b2e.png)

@alanmoo, are you able to assist with this? Thanks!

cc @edrushka @Saallen @KGorr Is there anywhere else we link to our Medium blog?

**Comment by KGorr** [comment]
@KevZawacki - some old emails linked to Medium posts (and therefore 1 or 2 of the Medium posts?), but that is all that I am aware of.

**Comment by KevZawacki** [comment]
@KGorr Thanks! I'll review past Medium posts for bad links.
