### ISSUE TITLE
Add our terms and Privacy policy to the website footer

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#92]
Hello 
I got an email from legal saying our website needs to have Mozilla Terms and privacy policy added ala Teach.mozilla.org
![screen shot 2016-09-13 at 16 36 30](https://cloud.githubusercontent.com/assets/10194015/18480341/417e2098-79d0-11e6-917d-03c0fe8955f0.png)

Is this possible to fix ? cc @edrushka @KevZawacki @alanmoo 
For the footer, including a link to the privacy policy is a legal requirement. Including the terms is an industry standard for websites that Mozilla follows for various reasons. Unfortunately the terms are still branded Webmaker, but in fact they apply across MLN.

**Comment by edrushka** [comment]
I think the only place for this is along the bottom footer, to the right of Participation Guidelines. 

Terms links to: https://beta.webmaker.org/#/legal?_k=0ihind (@hannahkane can you confirm this?)
Privacy links to: https://www.mozilla.org/en-US/privacy/websites/
