### ISSUE TITLE
Prepare all team images

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/2016.Mozillafestival.org#95]
Based on https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/86

Need to gather and crop images:
- [x] Space Wranglers (photos [here](https://docs.google.com/spreadsheets/d/100wmCld-YGysLHCpzYgovwctJkezPqQgFcOJ65mjyUk/edit#gid=1306798567))
- [x] Partner Organizations (logos/wordmarks) -- around 6-10 entries
- [x] Production Team (photos [here](https://mozillafestival.org/team))

If we secure corporate sponsorship, we'll need an additional section
- [ ] Sponsors -- likely around 1-5 entries (logos/wordmarks)

**Comment by mmmavis** [comment]
@kristinashu mind attaching hero banner image here as well?

**Comment by kristinashu** [comment]
@mmmavis yes, will do. Here are some of the cropped wrangler images but more are on their way https://drive.google.com/open?id=0B2irLVDJivhLU0U0emxpNnEtSEE

**Comment by kristinashu** [comment]
@mmmavis here is the home page image https://drive.google.com/drive/folders/0B2irLVDJivhLbm8yLTNDeUpMZFU?usp=sharing (these are two images: background and then the bright color bar along the bottom so that the background can resize but the bright bar is always visible along the bottom). Also updated https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/97 with the link.

**Comment by kristinashu** [comment]
Space Wranglers and Production Team photos are here: https://drive.google.com/drive/folders/0B2irLVDJivhLU0U0emxpNnEtSEE?usp=sharing

**Comment by kristinashu** [comment]
@edrushka do you know who the Partner Orgs are yet?

**Comment by edrushka** [comment]
- EPIK
- The Tate
- The V&A
- Arts Award
- BBC
- Ravensbourne

@Saallen who else? Met Office?

**Comment by kristinashu** [comment]
Oooh those sound great! Have they provided logos and/or descriptions?

**Comment by edrushka** [comment]
Not yet. We can track those down fairly quickly though.

**Comment by kristinashu** [comment]
@edrushka assign this ticket to you to collect Partner Org logos and descriptions

**Comment by edrushka** [comment]
Tracking in this shiny new spreadsheet: https://docs.google.com/spreadsheets/d/1W6fyaEFdwxEsRnuowmU7ZBiuo-fAvnrAHK--zhCrZdM/edit#gid=0

@marcwalsh @Saallen please add any logos you have and ensure all partners are on the list

**Comment by Saallen** [comment]
Going to share it on the Space wrangler call tomorrow

**Comment by kristinashu** [comment]
@edrushka are we going to have a description for each org or link the logo to their website?

**Comment by edrushka** [comment]
Link logo to website would be best. It will be hard to track down written descriptions from each. I will add the links to the spreadsheet.

**Comment by kristinashu** [comment]
Since we don't have descriptions, here's a new layout to work with logos only. (Note: logos are only placeholder until we have confirmation we can use them.) https://redpen.io/sue140ff7e7eda35ea

![website-03_team copy](https://cloud.githubusercontent.com/assets/1068783/18803863/28104e2a-81a9-11e6-892c-ff7c22c3476d.jpg)

cc @mmmavis

**Comment by edrushka** [comment]
All [partner logos](https://docs.google.com/spreadsheets/d/1W6fyaEFdwxEsRnuowmU7ZBiuo-fAvnrAHK--zhCrZdM/edit#gid=0) have been approved by the organizations 👍

**Comment by Saallen** [comment]
We are still missing people from this list- I seem to be missing my entry of the list of other partners will chase asap

**Comment by kristinashu** [comment]
We're still missing: 
- The Met office
- Teck4girls
- UCANTOO
- translate.org

Is it ok to launch the team pages without them?

**Comment by Saallen** [comment]
We do have them-  @kristinashu here https://drive.google.com/drive/folders/0B_B9-Ny1xBaRMzJpYmVHU0VVTFk and some of them uploaded them directly to the bio github issue

**Comment by edrushka** [comment]
@saallen can you unlock access to that doc

**Comment by kristinashu** [comment]
Got them, thanks!

**Comment by edrushka** [comment]
@Saallen we're still missing
- The Met Office
- Tech4Girls

If these arrive, please add them to the [Logos for partner section on team page spreadsheet](Logos https://docs.google.com/spreadsheets/d/1W6fyaEFdwxEsRnuowmU7ZBiuo-fAvnrAHK--zhCrZdM/edit#gid=0) and let us know in this ticket.

(Also just a note that any late SW bios and photos need to be updated to the [Bios tab](https://docs.google.com/spreadsheets/d/100wmCld-YGysLHCpzYgovwctJkezPqQgFcOJ65mjyUk/edit#gid=1306798567) of the Space Wrangler GH handles spreadsheet. These photos are becoming spread out across a variety of tickets, Google folders, dropbox folders - this spreadsheet is the only consolidation point.)
