### ISSUE TITLE
Implement Team page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/2016.Mozillafestival.org#96]
Based on design in https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/86

Comps https://redpen.io/p/nfb876a7968c868f1b

New page with tabs (using tab component and fellowship bio layout from https://science.mozilla.org/programs/fellowships/fellows). 

Tabs are:
- **Production:** currently exists as "[Team](https://mozillafestival.org/team)" link in the footer
- **Wranglers:** [mocked](https://redpen.io/br197c3cee3cc20738) up as a link from [Spaces & Sessions page](https://mozillafestival.org/spaces-and-sessions)
- **Sponsors:** doesn't currently exist or have content but we will need it
- **Partners:** doesn't currently exist or have content but we will need it

All the tabs have the same layout (circle image with name and bio).

We link to this tabbed page from:
- the footer (replacing the "Team" page link)
- bios on the Space & Sessions page (links to individual's name and bio)

Gathering images here https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/95

![website-03_team](https://cloud.githubusercontent.com/assets/1068783/18559996/959834d4-7b2e-11e6-9e94-9dddbf1f2a9b.jpg)

**Comment by mmmavis** [comment]
hey @kristinashu , what are the URLs for the 4 tabs?
- https://mozillafestival.org/team/production
- https://mozillafestival.org/team/wranglers
- https://mozillafestival.org/team/partners
- https://mozillafestival.org/team/sponsors

???

**Comment by kristinashu** [comment]
Sounds good to me. @edrushka?

**Comment by edrushka** [comment]
Works for me, but we still need @Saallen to sign off. I think #86 got closed before she approved.

Sarah - can you please confirm that the Team page can have 4 different groupings: production, wranglers, partners and sponsors (with those titles).

**Comment by kristinashu** [comment]
Space Wranglers and Production Team photos are here: https://drive.google.com/drive/folders/0B2irLVDJivhLU0U0emxpNnEtSEE?usp=sharing

Wrangler bios are here: https://docs.google.com/a/mozilla.com/spreadsheets/d/100wmCld-YGysLHCpzYgovwctJkezPqQgFcOJ65mjyUk/edit?usp=sharing

Team bios are the same as on current site: https://mozillafestival.org/team

@edrushka for ordering the bios, should they be:
- Team: keep the same order as on current site https://mozillafestival.org/team
- Wranglers: alphabetical? by last first name?

**Comment by edrushka** [comment]
I vote keeping them together by team, as we're currently doing

**Comment by kristinashu** [comment]
Ok, so we'll add section titles like on https://mozillafestival.org/spaces-and-sessions (for example Digital Arts and Culture, Journalism...)

**Comment by Saallen** [comment]
cc @chrislarry33 - do you want Mark S added to the team page as Festival Director?

**Comment by edrushka** [comment]
Logos are here for the partners tab: https://docs.google.com/spreadsheets/d/1W6fyaEFdwxEsRnuowmU7ZBiuo-fAvnrAHK--zhCrZdM/edit#gid=0

**Comment by Saallen** [comment]
Hey y'all, please only use logos and company names and titles which the Space wranglers have actually give us- if you have pulled something from the internet directly contact that wrangler to ensure we are can use that logo and we are representing them correctly

**Comment by kristinashu** [comment]
Ok, we'll only use logos provided in the doc above

**Comment by kristinashu** [comment]
@mmmavis please note:
- Production team and Wranglers tabs: good to go!
- Partners: still gathering logos
- Sponsors: might not have this tab so hold off on this one

**Comment by Saallen** [comment]
Argh- Github fail- didnt mean to close-

**Comment by edrushka** [comment]
Mark's bio ticket is here: https://github.com/MozillaFoundation/Mozfest2016_production/issues/159

**Comment by edrushka** [comment]
Mark's bio and photo are ready in MozillaFoundation/Mozfest2016_production#159

**Comment by kristinashu** [comment]
Cropped image of Marc is with the rest of the team photos in Drive: https://drive.google.com/drive/folders/0B2irLVDJivhLU0U0emxpNnEtSEE?usp=sharing

**Comment by Saallen** [comment]
Hey @kristinashu  can you update my title to Executive Festival Director
Thanks !

**Comment by kristinashu** [comment]
@mmmavis will have to do it

**Comment by kristinashu** [comment]
@mmmavis we have some new wrangler images: https://docs.google.com/spreadsheets/d/100wmCld-YGysLHCpzYgovwctJkezPqQgFcOJ65mjyUk/edit#gid=1306798567
[new wranglers.zip](https://github.com/MozillaFoundation/2016.Mozillafestival.org/files/509037/new.wranglers.zip)
Once these are added, there should only be 4 wranglers without an image or bio (everyone else should have an image + bio).

We also have two more logos to add: https://docs.google.com/spreadsheets/d/1W6fyaEFdwxEsRnuowmU7ZBiuo-fAvnrAHK--zhCrZdM/edit#gid=0
[logos.zip](https://github.com/MozillaFoundation/2016.Mozillafestival.org/files/509043/logos.zip)
The existing logos were looking big so I've scaled all of them down a little so please replace all of them.

**Comment by mmmavis** [comment]
any idea where we wanna link "UCanToo" and "Translate" to?

**Comment by kristinashu** [comment]
I believe http://www.ucantoo.org.uk/ and http://www.translate.org.za/

**Comment by mmmavis** [comment]
cool!

**Comment by Saallen** [comment]
Heyo- I think partners logos are good to go- I added some more

**Comment by kristinashu** [comment]
Here is how the page looks now:
<img width="864" alt="screen shot 2016-10-05 at 4 45 31 pm" src="https://cloud.githubusercontent.com/assets/1068783/19135669/388ce062-8b1b-11e6-960c-414fd7220759.png">

Based on the [spreadsheet](https://docs.google.com/spreadsheets/d/1W6fyaEFdwxEsRnuowmU7ZBiuo-fAvnrAHK--zhCrZdM/edit#gid=0), it sounds like we need to:
- remove EPIK
- add Tech4girls logo (no URL)
- add The Met Office (http://www.informaticslab.co.uk)

We should open new tickets for any additional logo updates. 

![tech4girls](https://cloud.githubusercontent.com/assets/1068783/19135596/c02ad232-8b1a-11e6-97d0-e5a3b072da6d.jpg)

![metoffice](https://cloud.githubusercontent.com/assets/1068783/19135845/b0bee3fe-8b1c-11e6-9750-730e6931b347.jpg)

**Comment by edrushka** [comment]
+1 remove EPIK - I am still in email discussion with Dorine about a replacement logo (looking like no at the moment).

**Comment by kristinashu** [comment]
yay!

**Comment by mmmavis** [comment]
I'll open a new PR to tackle the logo changes you mentioned: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/96#issuecomment-251832058

**Comment by edrushka** [comment]
pls cc me in that new ticket I finally got an answer on the EPIK logo

**Comment by mmmavis** [comment]
@edrushka To prevent the ticket to linger too long, [this "new" ticket](https://github.com/mozilla/mozillafestival.org/issues/461) will only cover

>  remove EPIK
>     add Tech4girls logo (no URL)
>     add The Met Office (http://www.informaticslab.co.uk)

When EPIK logo is ready please create a new ticket just for that and assign it to me. Thanks! 😉

**Comment by Saallen** [comment]
Hey, I just wanted to add open institute too. I added them to the logo list
yesterday. Can they go on this new update?
Sarah

**Comment by edrushka** [comment]
I will make a ticket for new EPIK and Open Institute logos.

**Comment by edrushka** [comment]
For reference, ticket is #108

**Comment by Saallen** [comment]
thanks yoooouu

Sarah Allen

Executive Festival Director, MozFest
Mozilla Foundation

Find out more about MozFest https://mozillafestival.org/ and follow the
conversation on twitter https://twitter.com/mozillafestival?lang=en-gb
