### ISSUE TITLE
Implement home page updates

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/2016.Mozillafestival.org#97]
Based on design in https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/81

Comp: https://redpen.io/tce99aae1e32140127

Updates:
- all copy
- "watch video" button
- image background https://drive.google.com/drive/folders/0B2irLVDJivhLbm8yLTNDeUpMZFU?usp=sharing (these are two images: background and then the bright color bar along the bottom so that the background can resize but the bright bar is always visible along the bottom)
- colors - see https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/94

**Comment by mmmavis** [comment]
@edrushka any idea where "Sign Up" link should go? https://redpen.io/tce99aae1e32140127

**Comment by edrushka** [comment]
Yes, to https://ti.to/Mozilla/mozfest-2016

**Comment by edrushka** [comment]
Not sure if there is an anchor on that page so you can jump right to Sign Up For Updates, which is mid-page.

**Comment by mmmavis** [comment]
@edrushka there's no anchor for "sign up for updates" - I'll use https://ti.to/Mozilla/mozfest-2016 .
