### ISSUE TITLE
Select D+D moderator

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/2016.Mozillafestival.org#98]
Someone to introduce each speaker and facilitate the Q&A.

We want someone polished with experience. @edrushka @Saallen Anyone in mind? Someone from AT?

**Comment by Saallen** [comment]
I would love gunner here, if he was willing.

**Comment by KevZawacki** [comment]
@Saallen That would be awesome. When / who can ask?

**Comment by Saallen** [comment]
Its already on my todo list

**Comment by KevZawacki** [comment]
Hey there. Any updates on our D+D moderator? Is Gunner in? :-)

**Comment by Saallen** [comment]
I will chase today

Sarah Allen

Events Manager and Mozilla Festival Producer
Mozilla Foundation

Find out more about MozFest https://mozillafestival.org/ and follow the
conversation on twitter https://twitter.com/mozillafestival?lang=en-gb

**Comment by KevZawacki** [comment]
Hi @Saallen, any word from Aspiration Tech on moderating the D+Ds?

Should I butt out? :-)

Just want to make sure we'll have the right person.

**Comment by Saallen** [comment]
Hey @KevZawacki Gunner and myself have been back and forth all week trying to a meeting time that suits. Hope to speak to him on Monday now- will update you

Why is there no butt emoji??

**Comment by KevZawacki** [comment]
Sarah Marshall! :-)
